import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as ExcelJS from 'exceljs';
import { FleetAsset, CrewMember, TripDispatch } from '../models/tms.models';
import { PORBIDO_LOGO_BASE64 } from '../constants/report-logo.constant';
import { formatAppDate } from '../utils/date-formatter';

export interface ReportPdfOptions {
  fileName: string;
  documentTitle: string; // 'TRUCK RECORDS' | 'CREW RECORDS'
  generationDate?: string;
  generatedBy?: string;
  headers: string[];
  rows: (string | number)[][];
  totalRow?: (string | number)[];
  columnStyles?: { [key: number]: { cellWidth?: number | 'auto' } };
}

export interface ReportExcelOptions {
  fileName: string;
  documentTitle: string; // 'TRUCK RECORDS' | 'CREW RECORDS'
  generationDate?: string;
  generatedBy?: string;
  headers: string[];
  rows: (string | number)[][];
  totalRow?: (string | number)[];
}

@Injectable({
  providedIn: 'root'
})
export class ReportExportService {

  // Standard Philippine Long Bond Paper (8.5 x 13 inches in mm)
  // LANDSCAPE: Width = 13" (330.2 mm), Height = 8.5" (215.9 mm)
  private readonly PAGE_WIDTH_MM = 330.2;
  private readonly PAGE_HEIGHT_MM = 215.9;
  private readonly MARGIN_MM = 25.4; // 1 inch (25.4 mm) on all sides

  /**
   * Generates an official Enterprise PDF report on 8.5 x 13" Long Bond Paper in LANDSCAPE
   * with centered unified header (Logo + Company Name & Address in same centered row block),
   * all metadata stacked on the left side (Document Title bold, Date & User non-bold),
   * center-aligned table headers with left-aligned row cells, Management Approval sign-off,
   * and standard "Page X of Y" footer.
   */
  exportEnterprisePdf(options: ReportPdfOptions): void {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: [this.PAGE_HEIGHT_MM, this.PAGE_WIDTH_MM] // [215.9, 330.2] mm
    });

    const totalPagesExp = '{total_pages_count_string}';
    const pageWidth = this.PAGE_WIDTH_MM;
    const pageHeight = this.PAGE_HEIGHT_MM;
    const margin = this.MARGIN_MM;
    const printableWidth = pageWidth - (margin * 2);

    let currentY = 10; // Top start
    const pageCenterX = pageWidth / 2;

    // ── 1. LOGO ON LEFT + CENTERED COMPANY NAME & ADDRESS ────────────────────
    const logoWidth = 64;
    const logoHeight = 18;
    const logoX = margin;
    const logoY = currentY;

    try {
      if (PORBIDO_LOGO_BASE64) {
        doc.addImage(PORBIDO_LOGO_BASE64, 'PNG', logoX, logoY, logoWidth, logoHeight);
      }
    } catch {
      // Fallback gracefully if image fails
    }

    // Centered Company Name (12pt Bold, Deep Navy Blue #1E3A5F)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 58, 95);
    doc.text('PORBIDO TRUCKING & HAULING SERVICE', pageCenterX, logoY + 6.5, { align: 'center' });

    // Centered Address (10pt Regular, Muted Slate #64748B - tight next line)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('ZONE 1 SAN VICENTE EAST, URDANETA CITY', pageCenterX, logoY + 12.5, { align: 'center' });

    // Snug divider spacing (2mm below logo bottom)
    currentY = logoY + logoHeight + 2;

    // Solid Deep Blue Divider Rule
    doc.setDrawColor(37, 99, 235); // #2563EB
    doc.setLineWidth(0.6);
    doc.line(margin, currentY, margin + printableWidth, currentY);

    currentY += 8; // Elegant breathing room between blue divider line and Document Title

    // ── 2. METADATA BLOCK (All Stacked on the Left Side) ─────────────────────
    const now = new Date();
    const formattedDate = options.generationDate || `${formatAppDate(now)} • ${now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })}`;

    // Line 1: Document Title (12pt, Bold - Only Title is Bold)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(38, 43, 53); // #262B35
    doc.text(options.documentTitle.toUpperCase(), margin, currentY);

    currentY += 4.5;

    // Line 2: Generation Date (10pt, Regular - Non-Bold)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // #475569
    doc.text(`Generation Date: ${formattedDate}`, margin, currentY);

    currentY += 4;

    // Line 3: Generated By (10pt, Regular - Non-Bold)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // #475569
    doc.text(`Generated By: ${options.generatedBy || 'Operations Administrator'}`, margin, currentY);

    currentY += 5; // Spacing before table starts

    // ── 3. DATA TABLE (Styled after Cargill Statement 29-50.pdf) ─────────────
    const tableBody = [...options.rows];
    if (options.totalRow) {
      tableBody.push(options.totalRow);
    }

    autoTable(doc, {
      startY: currentY,
      head: [options.headers],
      body: tableBody,
      theme: 'grid',
      margin: { left: margin, right: margin },
      styles: {
        font: 'helvetica',
        fontSize: 9,
        cellPadding: { top: 2.2, bottom: 2.2, left: 3, right: 3 },
        textColor: [38, 43, 53],      // #262B35
        lineColor: [203, 213, 225],    // Soft Slate Border #CBD5E1
        lineWidth: 0.2,
        valign: 'middle',
        halign: 'left'                // Body cells: Left-aligned
      },
      headStyles: {
        fillColor: [241, 245, 249],    // Soft Slate #F1F5F9 (matches Cargill 29-50 header)
        textColor: [30, 58, 95],       // Deep Blue #1E3A5F
        fontStyle: 'bold',
        fontSize: 9.5,
        halign: 'center',             // Header Titles: Center-aligned
        valign: 'middle',
        lineWidth: 0.3,
        lineColor: [148, 163, 184]
      },
      alternateRowStyles: {
        fillColor: [255, 255, 255]
      },
      columnStyles: options.columnStyles || {},
      didParseCell: (data) => {
        // Highlight and format TOTAL row at the bottom
        if (options.totalRow && data.row.index === tableBody.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [241, 245, 249];
          data.cell.styles.textColor = [30, 58, 95];
          data.cell.styles.lineWidth = { top: 0.4, bottom: 0.6, left: 0.2, right: 0.2 };
        }
      }
    });

    // Get table bottom Y position
    const finalY = (doc as any).lastAutoTable?.finalY || currentY + 40;

    // ── 4. OFFICIAL SIGN-OFF BLOCK (Approved by Management / Owner) ────────────
    const signBlockWidth = 70;
    const signX = pageWidth - margin - signBlockWidth;
    let signY = finalY + 12;

    // Check if sign-off fits on current page (leave 25mm margin for footer)
    if (signY + 22 > pageHeight - margin) {
      doc.addPage();
      signY = margin + 10;
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text('Approved by:', signX, signY);

    // Signature line
    doc.setDrawColor(100, 116, 139);
    doc.setLineWidth(0.4);
    doc.line(signX, signY + 12, signX + signBlockWidth, signY + 12);

    // Management / Owner Label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 58, 95);
    doc.text('MANAGEMENT / OWNER', signX + (signBlockWidth / 2), signY + 16.5, { align: 'center' });

    // ── 5. OFFICIAL AUDIT FOOTER & DYNAMIC TOTAL PAGE NUMBERS ─────────────────
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      const footerY = pageHeight - margin + 8;

      // Top divider rule above footer
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.2);
      doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);

      // Left Line 1: Confidentiality Notice (10pt regular)
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(
        'PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY',
        margin,
        footerY
      );

      // Left Line 2: System Generated Note (8pt muted)
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text('System-generated document', margin, footerY + 3.5);

      // Right: Standard "Page X of Y" (10pt regular)
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      const pageStr = `Page ${i} of ${totalPagesExp}`;
      doc.text(pageStr, pageWidth - margin, footerY, { align: 'right' });
    }

    // Replace total pages placeholder across all pages
    if (typeof doc.putTotalPages === 'function') {
      doc.putTotalPages(totalPagesExp);
    }

    // Trigger browser file download
    const cleanFileName = options.fileName.endsWith('.pdf') ? options.fileName : `${options.fileName}.pdf`;
    doc.save(cleanFileName);
  }

  // ─── HELPER: DATE_TIMESTAMP FORMATTER FOR FILENAMES ──────────────────────
  private getFileTimestamp(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, '0');
    const day = now.getDate().toString().padStart(2, '0');
    const hours = now.getHours().toString().padStart(2, '0');
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const seconds = now.getSeconds().toString().padStart(2, '0');
    return `${year}-${month}-${day}_${hours}-${minutes}-${seconds}`;
  }

  // ─── FLEET TRUCKS CONVENIENCE EXPORTERS ────────────────────────────────────

  exportTrucksToPdf(trucks: FleetAsset[]): void {
    const timestamp = this.getFileTimestamp();
    const headers = ['Plate No.', 'Capacity', 'Operational Status', 'Assigned Driver', 'Assigned Helper', 'Last Modified'];
    
    const rows = trucks.map(t => [
      t.plateNumber || 'N/A',
      `${t.tonsCapacity || 30} Tons`,
      t.status || 'Available',
      t.assignedCrew?.driver?.name && t.assignedCrew.driver.name !== 'None' ? t.assignedCrew.driver.name : 'Unassigned',
      t.assignedCrew?.helper?.name && t.assignedCrew.helper.name !== 'None' ? t.assignedCrew.helper.name : 'None',
      t.updatedAt ? formatAppDate(t.updatedAt) : '—'
    ]);

    const totalCapacity = trucks.reduce((sum, t) => sum + (t.tonsCapacity || 30), 0);
    const totalRow = ['TOTAL UNITS', `${totalCapacity} Tons Total`, `${trucks.length} Units`, '', '', ''];

    this.exportEnterprisePdf({
      fileName: `Porbido_Truck_Records_${timestamp}`,
      documentTitle: 'TRUCK RECORDS',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow,
      columnStyles: {
        0: { cellWidth: 40 }, // Plate No
        1: { cellWidth: 35 }, // Capacity
        2: { cellWidth: 42 }, // Status
        3: { cellWidth: 'auto' }, // Driver
        4: { cellWidth: 'auto' }, // Helper
        5: { cellWidth: 42 }  // Last Modified
      }
    });
  }

  // ─── CREW DIRECTORY CONVENIENCE EXPORTERS ──────────────────────────────────

  exportCrewToPdf(crew: CrewMember[]): void {
    const timestamp = this.getFileTimestamp();
    const headers = ['Full Name', 'Role', 'Employment Type', 'Contact Number', 'Status', 'Email Address'];
    
    const rows = crew.map(c => [
      c.name || 'N/A',
      c.role || 'Driver',
      c.type || 'Regular',
      c.contactNumber || c.phone || 'N/A',
      c.status || 'Active',
      c.email || '—'
    ]);

    const totalRow = ['TOTAL PERSONNEL', `${crew.length} Members`, '', '', '', ''];

    this.exportEnterprisePdf({
      fileName: `Porbido_Crew_Records_${timestamp}`,
      documentTitle: 'CREW RECORDS',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow,
      columnStyles: {
        0: { cellWidth: 'auto' }, // Full Name
        1: { cellWidth: 35 },     // Role
        2: { cellWidth: 38 },     // Type
        3: { cellWidth: 45 },     // Contact Number
        4: { cellWidth: 35 },     // Status
        5: { cellWidth: 'auto' }  // Email Address
      }
    });
  }

  // ─── ONGOING TRIPS CONVENIENCE EXPORTERS ──────────────────────────────────

  exportTripsToPdf(trips: TripDispatch[]): void {
    const timestamp = this.getFileTimestamp();
    const headers = ['Dispatch Date', 'Client', 'TLO #', 'Route', 'Fleet', 'Truck Rate', 'Cash on Hand', 'Status'];
    
    const getCash = (t: TripDispatch) => {
      const credits = (t.cohEntries || []).filter(e => e.type === 'CREDIT').reduce((sum, e) => sum + e.amount, 0);
      return credits > 0 ? credits : ((t as any).dispatchAllowance || 0);
    };

    const rows = trips.map(t => {
      const rateStr = `P${(t.truckRate || t.baseRate || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}\n${(t.weightTons || t.tonnage || 0).toFixed(2)} Tons`;
      const cohStr = `P${getCash(t).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      const fleetStr = `${t.plateNumber || '—'}\n${t.driverName || 'Unassigned'}${t.helperName && t.helperName !== 'None' && t.helperName !== 'Unassigned' ? ' • ' + t.helperName : ''}`;

      return [
        t.dispatchedDate || t.dispatchedAt ? formatAppDate(t.dispatchedDate || t.dispatchedAt) : '—',
        t.client || 'Cargill Philippines, Inc.',
        `${t.tloNumber}\nTrip# ${t.tripNumber || '—'}`,
        `[${t.routeTag === 'BACKLOAD' ? 'Backload' : 'Frontload'}]\n${t.origin || '—'} → ${t.destination || '—'}`,
        fleetStr,
        rateStr,
        cohStr,
        t.status || 'DISPATCHED'
      ];
    });

    const totalTons = trips.reduce((sum, t) => sum + (t.weightTons || t.tonnage || 0), 0);
    const totalCash = trips.reduce((sum, t) => sum + getCash(t), 0);

    const totalRow = [
      'TOTAL TRIPS', 
      `${trips.length} Active Trips`, 
      '', 
      '', 
      '', 
      `${totalTons.toFixed(2)} T Total`, 
      `P${totalCash.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 
      ''
    ];

    this.exportEnterprisePdf({
      fileName: `Porbido_Ongoing_Trips_${timestamp}`,
      documentTitle: 'ONGOING TRIPS',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow,
      columnStyles: {
        0: { cellWidth: 26 },     // Dispatch Date
        1: { cellWidth: 36 },     // Client
        2: { cellWidth: 28 },     // TLO #
        3: { cellWidth: 'auto' }, // Route
        4: { cellWidth: 42 },     // Fleet
        5: { cellWidth: 38 },     // Truck Rate
        6: { cellWidth: 34 },     // Cash on Hand
        7: { cellWidth: 26 }      // Status
      }
    });
  }

  // ─── COMPLETED TRIPS CONVENIENCE EXPORTERS ────────────────────────────────
  exportCompletedTripsToPdf(trips: TripDispatch[]): void {
    const timestamp = this.getFileTimestamp();
    const headers = ['TLO #', 'Delivered', 'Client', 'Route', 'Plate', 'Driver', 'Gross Freight', 'Expenses', 'COH Bal.', 'Net Profit', 'Billing Status'];

    const getExpenses = (t: TripDispatch) => {
      const debits = (t.cohEntries || []).filter(e => e.type === 'DEBIT').reduce((sum, e) => sum + e.amount, 0);
      return debits > 0 ? debits : (t.travelExpenses || 0) + (t.dieselExpenses || 0) + (t.foodExpenses || 0);
    };
    const getCOH = (t: TripDispatch) => {
      const credits = (t.cohEntries || []).filter(e => e.type === 'CREDIT').reduce((sum, e) => sum + e.amount, 0);
      return (credits > 0 ? credits : (t.truckRate ? 10000 : 0)) - getExpenses(t);
    };
    const getNet = (t: TripDispatch) => {
      if (t.netIncome !== undefined) return t.netIncome;
      return (t.totalFreightCharge || 0) - getExpenses(t) - ((t.driverSalary || 0) + (t.helperSalary || 0));
    };

    const rows = trips.map(t => {
      const delivered = t.deliveredDate || t.deliveredAt || t.dispatchedDate ? formatAppDate(t.deliveredDate || t.deliveredAt || t.dispatchedDate) : '—';
      const billingStatus = t.status === 'BILLED' ? 'Billed' : t.billingStatus === 'IN_BILLING' ? 'In Billing' : t.billingStatus === 'SUBMITTED' ? 'Submitted' : 'Ready to Bill';

      return [
        t.tloNumber ? `TLO #${t.tloNumber}` : '—',
        delivered,
        t.client || 'Cargill',
        `${t.origin || '—'} → ${t.destination || '—'}`,
        t.plateNumber || '—',
        t.driverName || 'Unassigned',
        `P${(t.totalFreightCharge || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        `P${getExpenses(t).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        `P${getCOH(t).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        `P${getNet(t).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        billingStatus
      ];
    });

    const totalFreight = trips.reduce((sum, t) => sum + (t.totalFreightCharge || 0), 0);
    const totalExpenses = trips.reduce((sum, t) => sum + getExpenses(t), 0);
    const totalNet = trips.reduce((sum, t) => sum + getNet(t), 0);

    const totalRow = [
      'TOTAL COMPLETED',
      `${trips.length} Trips`,
      '',
      '',
      '',
      '',
      `P${totalFreight.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      `P${totalExpenses.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      '',
      `P${totalNet.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      ''
    ];

    this.exportEnterprisePdf({
      fileName: `Porbido_Completed_Trips_${timestamp}`,
      documentTitle: 'COMPLETED TRIPS & LIQUIDATION',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow,
      columnStyles: {
        0: { cellWidth: 22 },     // TLO #
        1: { cellWidth: 22 },     // Delivered
        2: { cellWidth: 26 },     // Client
        3: { cellWidth: 'auto' }, // Route
        4: { cellWidth: 20 },     // Plate
        5: { cellWidth: 24 },     // Driver
        6: { cellWidth: 26 },     // Gross Freight
        7: { cellWidth: 24 },     // Expenses
        8: { cellWidth: 24 },     // COH Bal.
        9: { cellWidth: 26 },     // Net Profit
        10: { cellWidth: 24 }     // Billing Status
      }
    });
  }

  // ─── ENTERPRISE EXCEL EXPORTER WITH 2 FORMATTED WORKSHEETS (EXCELJS) ───────

  /**
   * Generates an official Enterprise Excel report (.xlsx) with 2 distinct worksheets:
   * 1. 'Company Info': Logo, Company Name, Address, Document Title, Audit Trail & Legal Footer
   * 2. 'Data': Formatted table with thin cell borders, colored headers, zebra striping, and auto column widths
   */
  async exportEnterpriseExcel(options: ReportExcelOptions): Promise<void> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Porbido TMS';
    workbook.lastModifiedBy = options.generatedBy || 'Operations Administrator';
    workbook.created = new Date();
    workbook.modified = new Date();

    const now = new Date();
    const formattedDate = options.generationDate || `${now.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    })} • ${now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })}`;

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 WORKSHEET 1: COMPANY INFO & AUDIT TRAIL
    // ─────────────────────────────────────────────────────────────────────────
    const infoSheet = workbook.addWorksheet('Company Info', {
      views: [{ showGridLines: true }]
    });

    infoSheet.columns = [
      { width: 5 },   // A: Left margin
      { width: 28 },  // B: Key
      { width: 55 },  // C: Value
      { width: 20 },  // D: Right margin
    ];

    // Embed Brand Logo
    if (PORBIDO_LOGO_BASE64) {
      try {
        const logoId = workbook.addImage({
          base64: PORBIDO_LOGO_BASE64,
          extension: 'png'
        });
        infoSheet.addImage(logoId, {
          tl: { col: 1, row: 1 },
          ext: { width: 220, height: 62 }
        });
      } catch {
        // Fallback gracefully
      }
    }

    // Row heights for logo spacing
    infoSheet.getRow(1).height = 18;
    infoSheet.getRow(2).height = 18;
    infoSheet.getRow(3).height = 18;
    infoSheet.getRow(4).height = 18;
    infoSheet.getRow(5).height = 12; // spacer

    // Row 6: Company Header Block
    const r6 = infoSheet.getRow(6);
    r6.getCell(2).value = 'PORBIDO TRUCKING & HAULING SERVICE';
    r6.getCell(2).font = { name: 'Arial', size: 13, bold: true, color: { argb: 'FF1E3A5F' } };
    r6.height = 20;

    const r7 = infoSheet.getRow(7);
    r7.getCell(2).value = 'ZONE 1 SAN VICENTE EAST, URDANETA CITY';
    r7.getCell(2).font = { name: 'Arial', size: 10, color: { argb: 'FF64748B' } };
    r7.height = 16;

    infoSheet.getRow(8).height = 12; // spacer

    // Row 9: Metadata Section Header
    const r9 = infoSheet.getRow(9);
    r9.getCell(2).value = 'DOCUMENT AUDIT PROFILE';
    r9.getCell(2).font = { name: 'Arial', size: 11, bold: true, color: { argb: 'FF1E3A5F' } };
    infoSheet.mergeCells('B9:C9');
    r9.getCell(2).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF1F5F9' }
    };
    r9.getCell(2).border = {
      top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
    };
    r9.height = 22;

    const metaItems = [
      { key: 'Document Title', val: options.documentTitle },
      { key: 'Active Scope', val: `${options.rows.length} Total Records Loaded` },
      { key: 'Generation Date & Time', val: formattedDate },
      { key: 'Generated By', val: options.generatedBy || 'Operations Administrator' },
      { key: 'Confidentiality Level', val: 'OFFICIAL USE ONLY (PROPRIETARY)' }
    ];

    let currentInfoRow = 10;
    for (const item of metaItems) {
      const row = infoSheet.getRow(currentInfoRow);
      row.getCell(2).value = item.key;
      row.getCell(2).font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF475569' } };
      row.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      row.getCell(2).border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };

      row.getCell(3).value = item.val;
      row.getCell(3).font = { name: 'Arial', size: 10, color: { argb: 'FF1E293B' } };
      row.getCell(3).border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };
      row.height = 20;
      currentInfoRow++;
    }

    currentInfoRow++; // spacer
    const rFooter1 = infoSheet.getRow(currentInfoRow);
    rFooter1.getCell(2).value = 'PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY';
    rFooter1.getCell(2).font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF94A3B8' } };
    currentInfoRow++;

    const rFooter2 = infoSheet.getRow(currentInfoRow);
    rFooter2.getCell(2).value = 'System-generated document';
    rFooter2.getCell(2).font = { name: 'Arial', size: 8.5, italic: true, color: { argb: 'FF94A3B8' } };

    // ─────────────────────────────────────────────────────────────────────────
    // 📊 WORKSHEET 2: DATA TABLE (Pure Formatted Table Only)
    // ─────────────────────────────────────────────────────────────────────────
    const dataSheet = workbook.addWorksheet('Data', {
      views: [{ showGridLines: true }]
    });

    // Row 1: Table Headers (Starts immediately at Row 1)
    const headerRow = dataSheet.getRow(1);
    headerRow.height = 26;
    options.headers.forEach((h, idx) => {
      const cell = headerRow.getCell(idx + 1);
      cell.value = h;
      cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFF1F5F9' } // Crisp soft slate header (matches Cargill 29-50)
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FF94A3B8' } },
        bottom: { style: 'medium', color: { argb: 'FF1E3A5F' } },
        left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
        right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
      };
    });

    // Rows 2+: Data Rows
    let rowCursor = 2;
    options.rows.forEach((rowData, rIdx) => {
      const row = dataSheet.getRow(rowCursor);
      row.height = 20;
      const isEven = rIdx % 2 === 1;

      rowData.forEach((val, cIdx) => {
        const cell = row.getCell(cIdx + 1);
        cell.value = val;
        cell.font = { name: 'Arial', size: 9.5, color: { argb: 'FF1E293B' } };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: isEven ? 'FFF8FAFC' : 'FFFFFFFF' }
        };
        cell.alignment = {
          vertical: 'middle',
          horizontal: typeof val === 'number' ? 'right' : 'left'
        };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
        };
      });
      rowCursor++;
    });

    // TOTAL Summary Row (if provided)
    if (options.totalRow) {
      const totRow = dataSheet.getRow(rowCursor);
      totRow.height = 24;
      options.totalRow.forEach((totVal, cIdx) => {
        const cell = totRow.getCell(cIdx + 1);
        cell.value = totVal;
        cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF1F5F9' }
        };
        cell.alignment = {
          vertical: 'middle',
          horizontal: typeof totVal === 'number' ? 'right' : 'left'
        };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FF94A3B8' } },
          bottom: { style: 'double', color: { argb: 'FF1E3A5F' } },
          left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
          right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
        };
      });
    }

    // Dynamic Auto Column Width Calculation
    options.headers.forEach((header, idx) => {
      let maxLen = header.length;
      options.rows.forEach(r => {
        const cellText = String(r[idx] ?? '');
        if (cellText.length > maxLen) {
          maxLen = cellText.length;
        }
      });
      if (options.totalRow && options.totalRow[idx]) {
        const totText = String(options.totalRow[idx]);
        if (totText.length > maxLen) {
          maxLen = totText.length;
        }
      }
      dataSheet.getColumn(idx + 1).width = Math.max(maxLen + 5, 16);
    });

    // Write buffer and trigger browser download
    const buffer = await workbook.xlsx.writeBuffer();
    const cleanFileName = options.fileName.endsWith('.xlsx')
      ? options.fileName
      : `${options.fileName}.xlsx`;

    const blob = new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = cleanFileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }

  async exportTrucksToExcel(trucks: FleetAsset[]): Promise<void> {
    const timestamp = this.getFileTimestamp();
    const headers = ['Plate Number', 'Capacity', 'Operational Status', 'Assigned Driver', 'Assigned Helper', 'Last Modified'];
    const rows = trucks.map(t => [
      t.plateNumber || 'N/A',
      `${t.tonsCapacity || 30} Tons`,
      t.status || 'Available',
      t.assignedCrew?.driver?.name && t.assignedCrew.driver.name !== 'None' ? t.assignedCrew.driver.name : 'Unassigned',
      t.assignedCrew?.helper?.name && t.assignedCrew.helper.name !== 'None' ? t.assignedCrew.helper.name : 'None',
      t.updatedAt ? formatAppDate(t.updatedAt) : '—'
    ]);

    const totalCapacity = trucks.reduce((sum, t) => sum + (t.tonsCapacity || 30), 0);
    const totalRow = ['TOTAL UNITS', `${totalCapacity} Tons Total`, `${trucks.length} Units`, '', '', ''];

    await this.exportEnterpriseExcel({
      fileName: `Porbido_Truck_Records_${timestamp}`,
      documentTitle: 'TRUCK RECORDS',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow
    });
  }

  async exportCrewToExcel(crew: CrewMember[]): Promise<void> {
    const timestamp = this.getFileTimestamp();
    const headers = ['Full Name', 'Role', 'Employment Type', 'Contact Number', 'Status', 'Email Address'];
    const rows = crew.map(c => [
      c.name || 'N/A',
      c.role || 'Driver',
      c.type || 'Regular',
      c.contactNumber || c.phone || 'N/A',
      c.status || 'Active',
      c.email || '—'
    ]);

    const totalRow = ['TOTAL PERSONNEL', `${crew.length} Members`, '', '', '', ''];

    await this.exportEnterpriseExcel({
      fileName: `Porbido_Crew_Records_${timestamp}`,
      documentTitle: 'CREW RECORDS',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow
    });
  }

  async exportTripsToExcel(trips: TripDispatch[]): Promise<void> {
    const timestamp = this.getFileTimestamp();
    const headers = ['Dispatch Date', 'Client', 'TLO #', 'Route', 'Fleet', 'Truck Rate', 'Cash on Hand', 'Status'];

    const getCash = (t: TripDispatch) => {
      const credits = (t.cohEntries || []).filter(e => e.type === 'CREDIT').reduce((sum, e) => sum + e.amount, 0);
      return credits > 0 ? credits : ((t as any).dispatchAllowance || 0);
    };

    const rows = trips.map(t => {
      const rateStr = `P${(t.truckRate || t.baseRate || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} (${(t.weightTons || t.tonnage || 0).toFixed(2)} Tons)`;
      const cohStr = `P${getCash(t).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      const fleetStr = `${t.plateNumber || '—'} - ${t.driverName || 'Unassigned'}${t.helperName && t.helperName !== 'None' && t.helperName !== 'Unassigned' ? ' / ' + t.helperName : ''}`;

      return [
        t.dispatchedDate || t.dispatchedAt ? formatAppDate(t.dispatchedDate || t.dispatchedAt) : '—',
        t.client || 'Cargill Philippines, Inc.',
        `${t.tloNumber} (Trip# ${t.tripNumber || '—'})`,
        `[${t.routeTag === 'BACKLOAD' ? 'Backload' : 'Frontload'}] ${t.origin || '—'} → ${t.destination || '—'}`,
        fleetStr,
        rateStr,
        cohStr,
        t.status || 'DISPATCHED'
      ];
    });

    const totalTons = trips.reduce((sum, t) => sum + (t.weightTons || t.tonnage || 0), 0);
    const totalCash = trips.reduce((sum, t) => sum + getCash(t), 0);

    const totalRow = [
      'TOTAL TRIPS', 
      `${trips.length} Active Trips`, 
      '', 
      '', 
      '', 
      `${totalTons.toFixed(2)} Tons Total`, 
      `P${totalCash.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 
      ''
    ];

    await this.exportEnterpriseExcel({
      fileName: `Porbido_Ongoing_Trips_${timestamp}`,
      documentTitle: 'ONGOING TRIPS',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow
    });
  }

  async exportCompletedTripsToExcel(trips: TripDispatch[]): Promise<void> {
    const timestamp = this.getFileTimestamp();
    const headers = [
      'TLO #', 
      'Trip #', 
      'Delivered Date', 
      'Client', 
      'Origin', 
      'Destination', 
      'Route Tag', 
      'Plate No.', 
      'Driver', 
      'Helper', 
      'Weight (Tons)', 
      'Gross Freight (PHP)', 
      'Expenses (PHP)', 
      'COH Balance (PHP)', 
      'Net Profit (PHP)', 
      'Billing Status'
    ];

    const getExpenses = (t: TripDispatch) => {
      const debits = (t.cohEntries || []).filter(e => e.type === 'DEBIT').reduce((sum, e) => sum + e.amount, 0);
      return debits > 0 ? debits : (t.travelExpenses || 0) + (t.dieselExpenses || 0) + (t.foodExpenses || 0);
    };
    const getCOH = (t: TripDispatch) => {
      const credits = (t.cohEntries || []).filter(e => e.type === 'CREDIT').reduce((sum, e) => sum + e.amount, 0);
      return (credits > 0 ? credits : (t.truckRate ? 10000 : 0)) - getExpenses(t);
    };
    const getNet = (t: TripDispatch) => {
      if (t.netIncome !== undefined) return t.netIncome;
      return (t.totalFreightCharge || 0) - getExpenses(t) - ((t.driverSalary || 0) + (t.helperSalary || 0));
    };

    const rows = trips.map(t => {
      const delivered = t.deliveredDate || t.deliveredAt || t.dispatchedDate ? formatAppDate(t.deliveredDate || t.deliveredAt || t.dispatchedDate) : '—';
      const billingStatus = t.status === 'BILLED' ? 'Billed' : t.billingStatus === 'IN_BILLING' ? 'In Billing' : t.billingStatus === 'SUBMITTED' ? 'Submitted' : 'Ready to Bill';

      return [
        t.tloNumber ? `TLO #${t.tloNumber}` : '—',
        t.tripNumber ? String(t.tripNumber) : '—',
        delivered,
        t.client || 'Cargill Philippines, Inc.',
        t.origin || '—',
        t.destination || '—',
        t.routeTag || 'FRONTLOAD',
        t.plateNumber || '—',
        t.driverName || 'Unassigned',
        t.helperName && t.helperName !== 'None' && t.helperName !== 'Unassigned' ? t.helperName : '—',
        t.tonnage || 0,
        t.totalFreightCharge || 0,
        getExpenses(t),
        getCOH(t),
        getNet(t),
        billingStatus
      ];
    });

    const totalTons = trips.reduce((sum, t) => sum + (t.tonnage || 0), 0);
    const totalFreight = trips.reduce((sum, t) => sum + (t.totalFreightCharge || 0), 0);
    const totalExpenses = trips.reduce((sum, t) => sum + getExpenses(t), 0);
    const totalNet = trips.reduce((sum, t) => sum + getNet(t), 0);

    const totalRow = [
      'TOTAL COMPLETED',
      `${trips.length} Trips`,
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      totalTons,
      totalFreight,
      totalExpenses,
      '',
      totalNet,
      ''
    ];

    await this.exportEnterpriseExcel({
      fileName: `Porbido_Completed_Trips_${timestamp}`,
      documentTitle: 'COMPLETED TRIPS & LIQUIDATION',
      generatedBy: 'Operations Administrator',
      headers,
      rows,
      totalRow
    });
  }
}

