import * as ExcelJS from 'exceljs';
import { PORBIDO_LOGO_BASE64 } from '../../constants/report-logo.constant';
import { ReportExcelOptions } from './export.types';

export class ExcelWorkbookBuilder {
  /**
   * Generates an official 2-Worksheet Excel file via ExcelJS:
   *  - Worksheet 1: "Company Info" (embedded PNG brand logo, document profile card, legal notice)
   *  - Worksheet 2: "Data" (pure, clean table starting at Row 1, styled headers, alternating rows, borders, total row)
   */
  static async buildEnterpriseExcel(options: ReportExcelOptions): Promise<void> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Porbido TMS';
    workbook.lastModifiedBy = options.generatedBy || 'Operations Administrator';
    workbook.created = new Date();
    workbook.modified = new Date();

    const now = new Date();
    const formattedDate = options.generationDate || `${now.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    })} • ${now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })}`;

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 WORKSHEET 1: COMPANY INFO & AUDIT TRAIL
    // ─────────────────────────────────────────────────────────────────────────
    const infoSheet = workbook.addWorksheet('Company Info', {
      views: [{ showGridLines: true }]
    });

    infoSheet.columns = [
      { width: 5 },   // A: Left margin
      { width: 28 },  // B: Key
      { width: 55 },  // C: Value
      { width: 20 },  // D: Right margin
    ];

    // Embed Brand Logo
    if (PORBIDO_LOGO_BASE64) {
      try {
        const logoId = workbook.addImage({
          base64: PORBIDO_LOGO_BASE64,
          extension: 'png'
        });
        infoSheet.addImage(logoId, {
          tl: { col: 1, row: 1 },
          ext: { width: 220, height: 62 }
        });
      } catch {
        // Fallback gracefully
      }
    }

    // Row heights for logo spacing
    infoSheet.getRow(1).height = 18;
    infoSheet.getRow(2).height = 18;
    infoSheet.getRow(3).height = 18;
    infoSheet.getRow(4).height = 18;
    infoSheet.getRow(5).height = 12; // spacer

    // Row 6: Company Header Block
    const r6 = infoSheet.getRow(6);
    r6.getCell(2).value = 'PORBIDO TRUCKING & HAULING SERVICE';
    r6.getCell(2).font = { name: 'Arial', size: 13, bold: true, color: { argb: 'FF1E3A5F' } };
    r6.height = 20;

    const r7 = infoSheet.getRow(7);
    r7.getCell(2).value = 'ZONE 1 SAN VICENTE EAST, URDANETA CITY';
    r7.getCell(2).font = { name: 'Arial', size: 10, color: { argb: 'FF64748B' } };
    r7.height = 16;

    // Row 8: Blue Divider Rule
    const r8 = infoSheet.getRow(8);
    for (let c = 2; c <= 3; c++) {
      r8.getCell(c).border = { bottom: { style: 'medium', color: { argb: 'FF2563EB' } } };
    }
    r8.height = 8;

    // Row 9: Spacer
    infoSheet.getRow(9).height = 10;

    // Row 10: Section Header — Document Audit Profile
    const r10 = infoSheet.getRow(10);
    r10.getCell(2).value = 'DOCUMENT AUDIT PROFILE';
    r10.getCell(2).font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    r10.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    r10.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    r10.height = 22;

    const profileData: [string, string][] = [
      ['Document Title', options.documentTitle.toUpperCase()],
      ['System Module', 'Porbido Transportation Management System (TMS)'],
      ['Generation Date & Time', formattedDate],
      ['Generated By', options.generatedBy || 'Operations Administrator'],
      ['Target Output Format', 'Microsoft Excel Spreadsheet (.xlsx)'],
      ['Total Data Records', `${options.rows.length} rows`],
      ['Paper Size Standard', '8.5" x 13" Philippine Long Bond Paper (Folio)']
    ];

    let infoRowIdx = 11;
    profileData.forEach(([k, v]) => {
      const r = infoSheet.getRow(infoRowIdx);
      r.getCell(2).value = k;
      r.getCell(2).font = { name: 'Arial', size: 9.5, bold: true, color: { argb: 'FF334155' } };
      r.getCell(3).value = v;
      r.getCell(3).font = { name: 'Arial', size: 9.5, color: { argb: 'FF475569' } };

      const borderStyle = { style: 'thin' as const, color: { argb: 'FFE2E8F0' } };
      r.getCell(2).border = { left: borderStyle, right: borderStyle, top: borderStyle, bottom: borderStyle };
      r.getCell(3).border = { left: borderStyle, right: borderStyle, top: borderStyle, bottom: borderStyle };
      r.height = 19;
      infoRowIdx++;
    });

    infoRowIdx += 2; // Spacer

    // Legal / Confidentiality Card
    const rLegal = infoSheet.getRow(infoRowIdx);
    rLegal.getCell(2).value = 'LEGAL & CONFIDENTIALITY NOTICE';
    rLegal.getCell(2).font = { name: 'Arial', size: 9.5, bold: true, color: { argb: 'FF92400E' } };
    rLegal.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF3C7' } };
    rLegal.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEF3C7' } };
    rLegal.height = 20;
    infoRowIdx++;

    const noticeRow = infoSheet.getRow(infoRowIdx);
    noticeRow.getCell(2).value = 'Notice';
    noticeRow.getCell(3).value = 'This document contains confidential and proprietary business records of Porbido Trucking & Hauling Service. Unauthorized reproduction, distribution, or alteration is strictly prohibited.';
    noticeRow.getCell(2).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF78350F' } };
    noticeRow.getCell(3).font = { name: 'Arial', size: 8.5, italic: true, color: { argb: 'FF78350F' } };
    noticeRow.getCell(3).alignment = { wrapText: true };
    noticeRow.height = 36;

    // ─────────────────────────────────────────────────────────────────────────
    // 📊 WORKSHEET 2: DATA
    // ─────────────────────────────────────────────────────────────────────────
    const dataSheet = workbook.addWorksheet('Data', {
      views: [{ showGridLines: true, state: 'frozen', ySplit: 1 }]
    });

    const thinBorder = {
      top: { style: 'thin' as const, color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin' as const, color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'thin' as const, color: { argb: 'FFCBD5E1' } },
      right: { style: 'thin' as const, color: { argb: 'FFCBD5E1' } }
    };

    // Row 1: Styled Headers
    const headerRow = dataSheet.getRow(1);
    options.headers.forEach((h, idx) => {
      const cell = headerRow.getCell(idx + 1);
      cell.value = h.toUpperCase();
      cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
      cell.border = thinBorder;
    });
    headerRow.height = 26;

    // Data Rows: Alternating Zebra Shading
    let currentDataRowIdx = 2;
    options.rows.forEach(rowVals => {
      const row = dataSheet.getRow(currentDataRowIdx);
      const isEven = currentDataRowIdx % 2 === 0;
      const fillColor = isEven ? 'FFFFFFFF' : 'FFF8FAFC';

      rowVals.forEach((val, idx) => {
        const cell = row.getCell(idx + 1);
        cell.value = val;
        cell.font = { name: 'Arial', size: 9.5, color: { argb: 'FF262B35' } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: fillColor } };
        cell.border = thinBorder;

        // Auto-align numbers to right, strings to left
        if (typeof val === 'number') {
          cell.alignment = { vertical: 'middle', horizontal: 'right' };
          cell.numFmt = '#,##0.00';
        } else {
          cell.alignment = { vertical: 'middle', horizontal: 'left' };
        }
      });

      row.height = 20;
      currentDataRowIdx++;
    });

    // TOTAL Summary Row (if provided)
    if (options.totalRow) {
      const totalRow = dataSheet.getRow(currentDataRowIdx);
      options.totalRow.forEach((val, idx) => {
        const cell = totalRow.getCell(idx + 1);
        cell.value = val;
        cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FF94A3B8' } },
          bottom: { style: 'double', color: { argb: 'FF1E3A5F' } },
          left: thinBorder.left,
          right: thinBorder.right
        };

        if (typeof val === 'number') {
          cell.alignment = { vertical: 'middle', horizontal: 'right' };
          cell.numFmt = '#,##0.00';
        } else {
          cell.alignment = { vertical: 'middle', horizontal: idx === 0 ? 'center' : 'left' };
        }
      });
      totalRow.height = 24;
    }

    // Auto-fit Column Widths with Minimum Safeguard
    options.headers.forEach((header, idx) => {
      let maxLen = header.length;
      options.rows.forEach(r => {
        const cellText = String(r[idx] ?? '');
        if (cellText.length > maxLen) {
          maxLen = cellText.length;
        }
      });
      if (options.totalRow && options.totalRow[idx]) {
        const totText = String(options.totalRow[idx]);
        if (totText.length > maxLen) {
          maxLen = totText.length;
        }
      }
      dataSheet.getColumn(idx + 1).width = Math.max(maxLen + 5, 16);
    });

    // Write buffer and trigger browser download
    const buffer = await workbook.xlsx.writeBuffer();
    const cleanFileName = options.fileName.endsWith('.xlsx')
      ? options.fileName
      : `${options.fileName}.xlsx`;

    const blob = new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = cleanFileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }
}
