import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PORBIDO_LOGO_BASE64 } from '../../constants/report-logo.constant';
import { formatAppDate } from '../../utils/date-formatter';
import { ReportPdfOptions } from './export.types';

export class PdfTableBuilder {
  // Standard Philippine Long Bond Paper (8.5 x 13 inches in mm)
  // LANDSCAPE: Width = 13" (330.2 mm), Height = 8.5" (215.9 mm)
  static readonly PAGE_WIDTH_MM = 330.2;
  static readonly PAGE_HEIGHT_MM = 215.9;
  static readonly MARGIN_MM = 25.4; // 1 inch (25.4 mm) on all sides

  /**
   * Official Corporate Header: Logo on Left + Centered Company Name & Address + Deep Blue Rule.
   * Returns the Y position immediately at the divider rule (30mm).
   */
  static drawCorporateHeader(targetDoc: jsPDF): number {
    const margin = this.MARGIN_MM;
    const pageWidth = this.PAGE_WIDTH_MM;
    const printableWidth = pageWidth - (margin * 2);
    const pageCenterX = pageWidth / 2;
    const logoY = 10;
    const logoWidth = 64;
    const logoHeight = 18;

    try {
      if (PORBIDO_LOGO_BASE64) {
        targetDoc.addImage(PORBIDO_LOGO_BASE64, 'PNG', margin, logoY, logoWidth, logoHeight);
      }
    } catch {
      // Fallback gracefully if image fails
    }

    // Centered Company Name (12pt Bold, Deep Navy Blue #1E3A5F)
    targetDoc.setFont('helvetica', 'bold');
    targetDoc.setFontSize(12);
    targetDoc.setTextColor(30, 58, 95);
    targetDoc.text('PORBIDO TRUCKING & HAULING SERVICE', pageCenterX, logoY + 6.5, { align: 'center' });

    // Centered Address (10pt Regular, Muted Slate #64748B)
    targetDoc.setFont('helvetica', 'normal');
    targetDoc.setFontSize(10);
    targetDoc.setTextColor(100, 116, 139);
    targetDoc.text('ZONE 1 SAN VICENTE EAST, URDANETA CITY', pageCenterX, logoY + 12.5, { align: 'center' });

    // Solid Deep Blue Divider Rule (2mm below logo)
    const dividerY = logoY + logoHeight + 2; // 30mm
    targetDoc.setDrawColor(37, 99, 235); // #2563EB
    targetDoc.setLineWidth(0.6);
    targetDoc.line(margin, dividerY, margin + printableWidth, dividerY);

    return dividerY; // 30mm
  }

  static getFileTimestamp(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, '0');
    const day = now.getDate().toString().padStart(2, '0');
    const hours = now.getHours().toString().padStart(2, '0');
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const seconds = now.getSeconds().toString().padStart(2, '0');
    return `${year}-${month}-${day}_${hours}-${minutes}-${seconds}`;
  }

  /**
   * Generates an official Enterprise PDF report on 8.5 x 13" Long Bond Paper in LANDSCAPE
   * with centered unified header (Logo + Company Name & Address in same centered row block),
   * all metadata stacked on the left side (Document Title bold, Date & User non-bold),
   * center-aligned table headers with left-aligned row cells, Management Approval sign-off,
   * and standard "Page X of Y" footer.
   */
  static buildEnterprisePdf(options: ReportPdfOptions): void {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: [this.PAGE_HEIGHT_MM, this.PAGE_WIDTH_MM] // [215.9, 330.2] mm
    });

    const totalPagesExp = '{total_pages_count_string}';
    const pageWidth = this.PAGE_WIDTH_MM;
    const pageHeight = this.PAGE_HEIGHT_MM;
    const margin = this.MARGIN_MM;

    // ── 1. LOGO ON LEFT + CENTERED COMPANY NAME & ADDRESS (Page 1) ───────────
    const dividerY = this.drawCorporateHeader(doc);
    let currentY = dividerY + 8; // Breathing room between blue divider line and Document Title (38mm)

    // ── 2. METADATA BLOCK (All Stacked on the Left Side) ─────────────────────
    const now = new Date();
    const formattedDate = options.generationDate || `${formatAppDate(now)} • ${now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })}`;

    // Line 1: Document Title (12pt, Bold - Only Title is Bold)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(38, 43, 53); // #262B35
    doc.text(options.documentTitle.toUpperCase(), margin, currentY);

    currentY += 4.5;

    // Line 2: Generation Date (10pt, Regular - Non-Bold)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // #475569
    doc.text(`Generation Date: ${formattedDate}`, margin, currentY);

    currentY += 4;

    // Line 3: Generated By (10pt, Regular - Non-Bold)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // #475569
    doc.text(`Generated By: ${options.generatedBy || 'Operations Administrator'}`, margin, currentY);

    currentY += 5; // Spacing before table starts

    // ── 3. DATA TABLE (Styled after Cargill Statement 29-50.pdf) ─────────────
    const tableBody = [...options.rows];
    if (options.totalRow) {
      tableBody.push(options.totalRow);
    }

    const isMultiRowHead = Array.isArray(options.headers[0]);
    const tableHead = isMultiRowHead ? options.headers : [options.headers];

    autoTable(doc, {
      startY: currentY,
      head: tableHead,
      body: tableBody,
      theme: 'grid',
      margin: { left: margin, right: margin, top: 44, bottom: margin },
      styles: {
        font: 'helvetica',
        fontSize: options.fontSize || 9,
        cellPadding: options.cellPadding || { top: 2.2, bottom: 2.2, left: 3, right: 3 },
        textColor: [38, 43, 53],      // #262B35
        lineColor: [203, 213, 225],    // Soft Slate Border #CBD5E1
        lineWidth: 0.2,
        valign: 'middle',
        halign: 'left'                // Body cells: Left-aligned
      },
      headStyles: {
        fillColor: [241, 245, 249],    // Soft Slate #F1F5F9 (matches Cargill 29-50 header)
        textColor: [30, 58, 95],       // Deep Blue #1E3A5F
        fontStyle: 'bold',
        fontSize: options.fontSize ? Math.min(options.fontSize + 0.2, 9.5) : 9.5,
        halign: 'center',             // Header Titles: Center-aligned
        valign: 'middle',
        lineWidth: 0.3,
        lineColor: [148, 163, 184]
      },
      alternateRowStyles: {
        fillColor: [255, 255, 255]
      },
      columnStyles: options.columnStyles || {},
      didDrawPage: (data) => {
        if (data.pageNumber > 1) {
          this.drawCorporateHeader(doc);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(10);
          doc.setTextColor(38, 43, 53);
          doc.text(`${options.documentTitle.toUpperCase()} (Cont.)`, margin, 36.5);
        }
      },
      didParseCell: (data) => {
        // Highlight and format TOTAL row at the bottom
        if (options.totalRow && data.row.index === tableBody.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [241, 245, 249];
          data.cell.styles.textColor = [30, 58, 95];
          data.cell.styles.lineWidth = { top: 0.4, bottom: 0.6, left: 0.2, right: 0.2 };
        }
      }
    });

    // Get table bottom Y position
    const finalY = (doc as any).lastAutoTable?.finalY || currentY + 40;

    // ── 4. OFFICIAL SIGN-OFF BLOCK (Approved by Management / Owner) ────────────
    const signBlockWidth = 70;
    const signX = pageWidth - margin - signBlockWidth;
    let signY = finalY + 12;

    // Check if sign-off fits on current page (leave 25mm margin for footer)
    if (signY + 22 > pageHeight - margin) {
      doc.addPage();
      const signHeaderY = this.drawCorporateHeader(doc);
      signY = signHeaderY + 12;
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text('Approved by:', signX, signY);

    // Signature line
    doc.setDrawColor(100, 116, 139);
    doc.setLineWidth(0.4);
    doc.line(signX, signY + 12, signX + signBlockWidth, signY + 12);

    // Management / Owner Label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 58, 95);
    doc.text('MANAGEMENT / OWNER', signX + (signBlockWidth / 2), signY + 16.5, { align: 'center' });

    // ── 5. OFFICIAL AUDIT FOOTER & DYNAMIC TOTAL PAGE NUMBERS ─────────────────
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      const footerY = pageHeight - margin + 8;

      // Top divider rule above footer
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.2);
      doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);

      // Left Line 1: Confidentiality Notice (includes generation timestamp starting on Page 2)
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);

      const confidentialText = i === 1
        ? 'PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY'
        : `PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY | ${formattedDate}`;

      doc.text(confidentialText, margin, footerY);

      // Left Line 2: System Generated Note (8pt muted)
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text('System-generated document', margin, footerY + 3.5);

      // Right: Standard "Page X of Y" (10pt regular)
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      const pageStr = `Page ${i} of ${totalPagesExp}`;
      doc.text(pageStr, pageWidth - margin, footerY, { align: 'right' });
    }

    // Replace total pages placeholder across all pages
    if (typeof doc.putTotalPages === 'function') {
      doc.putTotalPages(totalPagesExp);
    }

    // Trigger browser file download
    const cleanFileName = options.fileName.endsWith('.pdf') ? options.fileName : `${options.fileName}.pdf`;
    doc.save(cleanFileName);
  }
}
