import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { TripDispatch, COHEntry } from '../../models/tms.models';
import { formatAppDate } from '../../utils/date-formatter';
import { FirebaseService } from '../../services/firebase.service';
import { TripDossierProofItem } from './export.types';
import { PdfTableBuilder } from './pdf-table.builder';
import { TripFinancialMetricsCalculator } from './trip-financial-metrics.calculator';

export class TripDossierPdfBuilder {
  static async build(
    trip: TripDispatch,
    cohEntries: COHEntry[] = [],
    proofs: TripDossierProofItem[] = [],
    firebaseService?: FirebaseService
  ): Promise<void> {
    const timestamp = PdfTableBuilder.getFileTimestamp();
    const tloNum = trip.tloNumber ? String(trip.tloNumber) : '—';
    const tripNum = trip.tripNumber !== undefined ? String(trip.tripNumber) : '1';
    const plateNum = trip.plateNumber || '—';
    const driver = trip.driverName || 'Unassigned';
    const metrics = TripFinancialMetricsCalculator.compute(trip, cohEntries);

    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: [PdfTableBuilder.PAGE_HEIGHT_MM, PdfTableBuilder.PAGE_WIDTH_MM] // [215.9, 330.2] mm
    });

    const totalPagesExp = '{total_pages_count_string}';
    const pageWidth = PdfTableBuilder.PAGE_WIDTH_MM;
    const pageHeight = PdfTableBuilder.PAGE_HEIGHT_MM;
    const margin = PdfTableBuilder.MARGIN_MM; // 25.4 mm
    const printableWidth = pageWidth - (margin * 2); // 279.4 mm

    const now = new Date();
    const formattedDate = `${formatAppDate(now)} • ${now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })}`;

    // Currency formatters using standard 'P' for WinAnsi / jsPDF compatibility
    const fmtMoney = (val: number): string => {
      return `P${(val || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    };

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 1ST PAGE: CORPORATE HEADER, OVERVIEW, OPERATIONS, BILLING & FINANCIALS
    // ─────────────────────────────────────────────────────────────────────────
    const dividerY = PdfTableBuilder.drawCorporateHeader(doc);
    let currentY = dividerY + 5.5;

    // Stacked Left Metadata
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(38, 43, 53);
    doc.text('TRIP DETAILS REPORT', margin, currentY);

    currentY += 4.2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(71, 85, 105);
    doc.text(`Generated: ${formattedDate}`, margin, currentY);

    currentY += 3.8;
    doc.text('Generated By: Operations Administrator', margin, currentY);

    currentY += 5.0;

    // Row 1: 3 Tables Side-by-Side (Overview, Operations, Billing Details)
    const gap = 5.0;
    const colWidth = (printableWidth - (gap * 2)) / 3; // ~89.8 mm each
    const col1X = margin;
    const col2X = margin + colWidth + gap;
    const col3X = margin + (colWidth + gap) * 2;
    const row1StartY = currentY;

    // Table 1: OVERVIEW
    const overviewRows: [string, string][] = [
      ['TLO Number', tloNum],
      ['Trip Number', tripNum],
      ['Client', trip.client || 'Cargill PH, Inc.'],
      ['Dispatched Date', formatAppDate(trip.dispatchedDate || trip.dispatchedAt) || '—'],
      ['Trip Status', (trip.status || 'Completed').replace(/_/g, ' ')],
      ['Completed Date', formatAppDate(trip.deliveredDate || trip.deliveredAt || trip.updatedAt) || '—']
    ];

    autoTable(doc, {
      startY: row1StartY,
      margin: { left: col1X },
      tableWidth: colWidth,
      head: [['OVERVIEW', '']],
      body: overviewRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.3, bottom: 1.3, left: 2.2, right: 2.2 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5,
        halign: 'left'
      },
      columnStyles: {
        0: { cellWidth: 38, fontStyle: 'bold', textColor: [30, 58, 95] },
        1: { cellWidth: colWidth - 38, textColor: [38, 43, 53] }
      }
    });
    const t1FinalY = (doc as any).lastAutoTable.finalY;

    // Table 2: OPERATIONS
    const routeTagStr = `${trip.routeTag || 'FRONTLOAD'} - ${trip.origin || trip.originFrom || 'Subic Port'} - ${trip.destination || trip.destinationTo || 'Bulacan Port'}`;
    const operationsRows: [string, string][] = [
      ['Route Tag', routeTagStr],
      ['Fleet', plateNum],
      ['Driver', driver],
      ['Helper', trip.helperName && trip.helperName !== 'None' ? trip.helperName : '—'],
      ['Commodity Cargo', trip.commodity || 'General Cargos'],
      ['Number of Bags', trip.bagCount ? `${trip.bagCount} Bags` : (trip.commodity ? `${metrics.tonnage || 50} Bags` : '50 Bags')]
    ];

    autoTable(doc, {
      startY: row1StartY,
      margin: { left: col2X },
      tableWidth: colWidth,
      head: [['OPERATIONS', '']],
      body: operationsRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.3, bottom: 1.3, left: 2.2, right: 2.2 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5,
        halign: 'left'
      },
      columnStyles: {
        0: { cellWidth: 36, fontStyle: 'bold', textColor: [30, 58, 95] },
        1: { cellWidth: colWidth - 36, textColor: [38, 43, 53] }
      }
    });
    const t2FinalY = (doc as any).lastAutoTable.finalY;

    // Table 3: BILLING DETAILS
    const billingRows: [string, string][] = [
      ['Billing Status', ''],
      ['Billing Reference / SA Number', ''],
      ['Billing Date', ''],
      ['Billing Amount', ''],
      ['Reconciliation Reference', ''],
      ['Reconciliation Status', '']
    ];

    autoTable(doc, {
      startY: row1StartY,
      margin: { left: col3X },
      tableWidth: colWidth,
      head: [['BILLING DETAILS', '']],
      body: billingRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.3, bottom: 1.3, left: 2.2, right: 2.2 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5,
        halign: 'left'
      },
      columnStyles: {
        0: { cellWidth: 50, fontStyle: 'bold', textColor: [30, 58, 95] },
        1: { cellWidth: colWidth - 50, textColor: [38, 43, 53] }
      }
    });
    const t3FinalY = (doc as any).lastAutoTable.finalY;

    currentY = Math.max(t1FinalY, t2FinalY, t3FinalY) + 4.5;

    // Row 2: 3 Tables Based on the 3 Financials Cards
    const row2StartY = currentY;

    // Table A: GROSS FREIGHT REVENUE
    const rateBadge = trip.rateType === 'FLAT_RATE' ? 'FLAT_RATE' : 'PER_TON';
    const grossRows: [string, string][] = [
      ['Master Base Rate', `${fmtMoney(metrics.baseRate)} / ton`],
      ['Scale Weight (Tonnage)', `${metrics.tonnage} Tons`],
      ['Base Freight Subtotal', fmtMoney(metrics.tonnage * metrics.baseRate)],
      ['Re-route Fee', fmtMoney(trip.rerouteFeeApplied ? 3600 : 0)],
      ['Extra / Demurrage Fees', fmtMoney(trip.extraFees || 0)],
      ['Gross Freight Revenue', fmtMoney(metrics.grossFreight)]
    ];

    autoTable(doc, {
      startY: row2StartY,
      margin: { left: col1X },
      tableWidth: colWidth,
      head: [['GROSS FREIGHT REVENUE', rateBadge]],
      body: grossRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.2, bottom: 1.2, left: 2.2, right: 3 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5
      },
      columnStyles: {
        0: { cellWidth: 45, textColor: [71, 85, 105] },
        1: { cellWidth: colWidth - 45, halign: 'right', fontStyle: 'bold', textColor: [38, 43, 53] }
      },
      didParseCell: (data) => {
        if (data.row.index === 5 && data.section === 'body') {
          data.cell.styles.fillColor = [239, 246, 255];
          data.cell.styles.fontStyle = 'bold';
          if (data.column.index === 1) {
            data.cell.styles.textColor = [37, 99, 235];
          }
        }
      }
    });
    const taFinalY = (doc as any).lastAutoTable.finalY;

    // Table B: CREW EXPENSES
    const expenseRows: [string, string][] = [
      ['Fuel', fmtMoney(metrics.fuel)],
      ['Toll Fees', fmtMoney(metrics.toll)],
      ['Meals / Foods', fmtMoney(metrics.meals)],
      ['Maintenance', fmtMoney(metrics.maintenance)],
      ['Others', fmtMoney(metrics.others)],
      ['Total Crew Expenses', fmtMoney(metrics.totalDebit)]
    ];

    autoTable(doc, {
      startY: row2StartY,
      margin: { left: col2X },
      tableWidth: colWidth,
      head: [['CREW EXPENSES', 'OUTFLOW']],
      body: expenseRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.2, bottom: 1.2, left: 2.2, right: 3 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5
      },
      columnStyles: {
        0: { cellWidth: 43, textColor: [71, 85, 105] },
        1: { cellWidth: colWidth - 43, halign: 'right', fontStyle: 'bold', textColor: [225, 29, 72] }
      },
      didParseCell: (data) => {
        if (data.row.index === 5 && data.section === 'body') {
          data.cell.styles.fillColor = [255, 241, 242];
          data.cell.styles.fontStyle = 'bold';
          if (data.column.index === 1) {
            data.cell.styles.textColor = [225, 29, 72];
          }
        }
      }
    });
    const tbFinalY = (doc as any).lastAutoTable.finalY;

    // Table C: CREW COMPENSATION
    const payrollRows: [string, string][] = [
      ['Driver Salary Pay', fmtMoney(metrics.driverSalary)],
      ['Helper Salary Pay', fmtMoney(metrics.helperSalary)],
      ['', ''],
      ['', ''],
      ['', ''],
      ['Total Crew Payroll', fmtMoney(metrics.totalCrewPayroll)]
    ];

    autoTable(doc, {
      startY: row2StartY,
      margin: { left: col3X },
      tableWidth: colWidth,
      head: [['CREW COMPENSATION', 'PAYROLL']],
      body: payrollRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.2, bottom: 1.2, left: 2.2, right: 3 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5
      },
      columnStyles: {
        0: { cellWidth: 43, textColor: [71, 85, 105] },
        1: { cellWidth: colWidth - 43, halign: 'right', fontStyle: 'bold', textColor: [38, 43, 53] }
      },
      didParseCell: (data) => {
        if (data.row.index === 5 && data.section === 'body') {
          data.cell.styles.fillColor = [245, 243, 255];
          data.cell.styles.fontStyle = 'bold';
          if (data.column.index === 1) {
            data.cell.styles.textColor = [37, 99, 235];
          }
        }
      }
    });
    const tcFinalY = (doc as any).lastAutoTable.finalY;

    // Extra vertical breathing room before summary section
    currentY = Math.max(taFinalY, tbFinalY, tcFinalY) + 9.5;

    // Row 3: Trip Financial Statement Table (Summary)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 58, 95);
    doc.text('Trip Financial Statement', margin, currentY);

    const statementRows: [string, string, string, string][] = [
      [
        '1. Gross Freight Revenue',
        'REVENUE',
        fmtMoney(metrics.grossFreight),
        `+${fmtMoney(metrics.grossFreight)}`
      ],
      [
        '2. Crew Expenses (Fuel, Toll Fees, Meals / Foods, Maintenance, Others)',
        'OUTFLOW',
        fmtMoney(metrics.totalDebit),
        `-${fmtMoney(metrics.totalDebit)}`
      ],
      [
        '3. Crew Compensation (Driver & Helper Salaries)',
        'PAYROLL',
        fmtMoney(metrics.totalCrewPayroll),
        `-${fmtMoney(metrics.totalCrewPayroll)}`
      ],
      [
        'NET TRIP INCOME & PROFITABILITY',
        `${metrics.margin.toFixed(1)}% NET MARGIN`,
        '',
        fmtMoney(metrics.netTripIncome)
      ]
    ];

    autoTable(doc, {
      startY: currentY + 4.5,
      margin: { left: margin, right: margin },
      tableWidth: printableWidth,
      head: [['ITEM', 'CATEGORY', 'SUBTOTAL (P)', 'NET IMPACT']],
      body: statementRows,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.5, bottom: 1.5, left: 3, right: 3.5 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5,
        halign: 'center'
      },
      columnStyles: {
        0: { cellWidth: 135.4, halign: 'left', fontStyle: 'bold', textColor: [30, 58, 95] },
        1: { cellWidth: 36, halign: 'center', fontStyle: 'bold' },
        2: { cellWidth: 54, halign: 'right' },
        3: { cellWidth: 54, halign: 'right', fontStyle: 'bold' }
      },
      didParseCell: (data) => {
        if (data.section === 'body') {
          if (data.row.index === 0) {
            if (data.column.index === 1) data.cell.styles.textColor = [37, 99, 235];
            if (data.column.index === 3) data.cell.styles.textColor = [22, 163, 74];
          } else if (data.row.index === 1) {
            if (data.column.index === 1 || data.column.index === 3) data.cell.styles.textColor = [225, 29, 72];
          } else if (data.row.index === 2) {
            if (data.column.index === 1) data.cell.styles.textColor = [100, 116, 139];
            if (data.column.index === 3) data.cell.styles.textColor = [225, 29, 72];
          } else if (data.row.index === 3) {
            data.cell.styles.fillColor = [240, 253, 244];
            data.cell.styles.fontStyle = 'bold';
            if (data.column.index === 1 || data.column.index === 3) {
              data.cell.styles.textColor = [22, 163, 74];
            }
          }
        }
      }
    });

    const p1TableFinalY = (doc as any).lastAutoTable.finalY;
    const signY = Math.min(p1TableFinalY + 4.5, pageHeight - margin - 12);

    // Official Approval Block (Only on Page 1)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text('Approved by:', pageWidth - margin - 65, signY);

    doc.setDrawColor(203, 213, 225);
    doc.setLineWidth(0.4);
    doc.line(pageWidth - margin - 65, signY + 8, pageWidth - margin, signY + 8);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(30, 58, 95);
    doc.text('MANAGEMENT / OWNER', pageWidth - margin - 65, signY + 12);

    // Helper: Simplified Header for Page 2 and all subsequent pages
    const drawSimplifiedHeader = (targetDoc: jsPDF): number => {
      const headerDividerY = PdfTableBuilder.drawCorporateHeader(targetDoc);
      let y = headerDividerY + 5.5; // ~35.5mm

      // Line 1: TLO Number as bold title
      targetDoc.setFont('helvetica', 'bold');
      targetDoc.setFontSize(11);
      targetDoc.setTextColor(38, 43, 53);
      targetDoc.text(`TLO Number: ${tloNum}`, margin, y);

      // Subsequent lines: clean data-only values without redundant labels
      y += 4.0;
      targetDoc.setFont('helvetica', 'normal');
      targetDoc.setFontSize(8.5);
      targetDoc.setTextColor(71, 85, 105);

      const dispatchDateStr = formatAppDate(trip.dispatchedDate || trip.dispatchedAt) || '—';
      targetDoc.text(`Trip Number: ${tripNum} • ${dispatchDateStr}`, margin, y);

      y += 3.6;
      const rTagStr = (trip.routeTag || 'FRONTLOAD').toUpperCase();
      const originStr = trip.origin || trip.originFrom || 'Subic Port';
      const destStr = trip.destination || trip.destinationTo || 'Bulacan Port';
      targetDoc.text(`${rTagStr} • ${originStr} >  ${destStr}`, margin, y);

      y += 3.6;
      const statusStr = ((trip.status || 'COMPLETED').replace(/_/g, ' ')).toUpperCase();
      const compDateStr = formatAppDate(trip.deliveredDate || trip.deliveredAt || trip.updatedAt) || '—';
      targetDoc.text(`${statusStr} • ${compDateStr}`, margin, y);

      y += 3.5;
      targetDoc.setDrawColor(226, 232, 240);
      targetDoc.setLineWidth(0.3);
      targetDoc.line(margin, y, margin + printableWidth, y);

      return y + 5.0; // Content start Y (~55.2mm)
    };

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 2ND PAGE: CASH FLOW SUMMARY & TRANSACTIONS TABLE
    // ─────────────────────────────────────────────────────────────────────────
    doc.addPage();
    let p2Y = drawSimplifiedHeader(doc);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 58, 95);
    doc.text('Cash Flow Summary', margin, p2Y);

    p2Y += 4.0;

    // 4-Column Cash Flow Summary Table
    const col4Width = printableWidth / 4; // 69.85 mm each
    const prevSub = metrics.prevType === 'BALANCED'
      ? 'Fully Liquidated'
      : (metrics.prevType === 'SHORTAGE' ? 'Shortage Carried Over' : 'Surplus Carried Over');
    const endSub = metrics.endingType === 'SURPLUS'
      ? 'Cash Surplus'
      : (metrics.endingType === 'DEFICIT' ? 'Cash Shortage' : 'Balanced');

    autoTable(doc, {
      startY: p2Y,
      margin: { left: margin, right: margin },
      tableWidth: printableWidth,
      head: [['PREVIOUS CARRYOVER', 'CASH ON HAND', 'CREW EXPENSES', 'ENDING CASH ON HAND']],
      body: [
        [
          fmtMoney(Math.abs(metrics.signedCarryover)),
          fmtMoney(metrics.totalCredit),
          fmtMoney(metrics.totalDebit),
          fmtMoney(metrics.endingBalance)
        ],
        [
          prevSub,
          'Initial & additional cash',
          'Fuel, toll, meals and others',
          endSub
        ]
      ],
      theme: 'grid',
      styles: {
        font: 'helvetica',
        halign: 'center',
        valign: 'middle',
        lineColor: [203, 213, 225],
        lineWidth: 0.2
      },
      headStyles: {
        fillColor: [248, 250, 252],
        textColor: [100, 116, 139],
        fontSize: 7,
        fontStyle: 'bold',
        cellPadding: 1.6
      },
      columnStyles: {
        0: { cellWidth: col4Width },
        1: { cellWidth: col4Width },
        2: { cellWidth: col4Width },
        3: { cellWidth: col4Width }
      },
      didParseCell: (data) => {
        if (data.section === 'body') {
          if (data.row.index === 0) {
            data.cell.styles.fontSize = 9.5;
            data.cell.styles.fontStyle = 'bold';
            data.cell.styles.cellPadding = { top: 2, bottom: 1, left: 2, right: 2 };
            if (data.column.index === 0) data.cell.styles.textColor = [30, 58, 95];
            if (data.column.index === 1) data.cell.styles.textColor = [22, 163, 74];
            if (data.column.index === 2) data.cell.styles.textColor = [225, 29, 72];
            if (data.column.index === 3) data.cell.styles.textColor = [30, 58, 95];
          } else {
            data.cell.styles.fontSize = 6.8;
            data.cell.styles.fontStyle = 'normal';
            data.cell.styles.textColor = [100, 116, 139];
            data.cell.styles.cellPadding = { top: 0.5, bottom: 2, left: 2, right: 2 };
            if (data.column.index === 3 && metrics.endingType === 'SURPLUS') {
              data.cell.styles.textColor = [22, 163, 74];
            }
          }
        }
      }
    });

    const p2SummaryFinalY = (doc as any).lastAutoTable.finalY;
    let p2TransStartY = p2SummaryFinalY + 5.5;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 58, 95);
    doc.text('Transactions', margin, p2TransStartY);

    p2TransStartY += 4.0;

    // Transactions Table (DATE, DESCRIPTION, CREDIT, DEBIT, BALANCE)
    let currentRunBal = metrics.startingCOH;
    const transRows = cohEntries.map((e) => {
      const amt = Number(e.amount) || 0;
      const isCredit = e.type === 'CREDIT';
      if (isCredit) currentRunBal += amt;
      else currentRunBal -= amt;

      const dateStr = formatAppDate(e.date || e.timestamp) || '—';
      const descStr = e.description || '—';
      const creditStr = isCredit ? `+${fmtMoney(amt)}` : '';
      const debitStr = !isCredit ? `-${fmtMoney(amt)}` : '';
      const balStr = fmtMoney(currentRunBal);

      return [dateStr, descStr, creditStr, debitStr, balStr];
    });

    const totalTransRow = [
      'TOTAL',
      `${cohEntries.length} Transactions`,
      `+${fmtMoney(metrics.totalCredit)}`,
      `-${fmtMoney(metrics.totalDebit)}`,
      fmtMoney(metrics.endingBalance)
    ];

    autoTable(doc, {
      startY: p2TransStartY,
      margin: { left: margin, right: margin, top: 55, bottom: 14 },
      tableWidth: printableWidth,
      head: [['DATE', 'DESCRIPTION', 'CREDIT', 'DEBIT', 'BALANCE']],
      body: [...transRows, totalTransRow],
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: { top: 1.5, bottom: 1.5, left: 2.5, right: 3.5 },
        textColor: [38, 43, 53],
        lineColor: [203, 213, 225],
        lineWidth: 0.2,
        valign: 'middle'
      },
      headStyles: {
        fillColor: [241, 245, 249],
        textColor: [30, 58, 95],
        fontStyle: 'bold',
        fontSize: 7.5,
        halign: 'center'
      },
      columnStyles: {
        0: { cellWidth: 32, halign: 'left' },
        1: { cellWidth: 119.4, halign: 'left' },
        2: { cellWidth: 42, halign: 'right', fontStyle: 'bold', textColor: [22, 163, 74] },
        3: { cellWidth: 42, halign: 'right', fontStyle: 'bold', textColor: [225, 29, 72] },
        4: { cellWidth: 44, halign: 'right', fontStyle: 'bold', textColor: [30, 58, 95] }
      },
      didDrawPage: (data) => {
        if (data.pageNumber > 1) {
          drawSimplifiedHeader(doc);
        }
      },
      didParseCell: (data) => {
        if (data.row.index === transRows.length && data.section === 'body') {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [241, 245, 249];
          if (data.column.index === 1) {
            data.cell.styles.fontStyle = 'normal';
            data.cell.styles.textColor = [100, 116, 139];
          }
        }
      }
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 LAST PAGE: PROOF / RECEIPT IMAGES (3x2 Grid, Max 6 Per Page)
    // ─────────────────────────────────────────────────────────────────────────
    doc.addPage();
    let p3ImgY = drawSimplifiedHeader(doc);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 58, 95);
    doc.text('Proof / Receipt Images', margin, p3ImgY);

    // Consolidate images
    const imageUrls: string[] = [];
    if (trip.podImageUrl) {
      imageUrls.push(trip.podImageUrl);
    }
    proofs.forEach((p) => {
      const u = (p as any).dataUrl || (p as any).proofDataUrl || p.url;
      if (u && !imageUrls.includes(u)) {
        imageUrls.push(u);
      }
    });
    cohEntries.forEach((e) => {
      const u = e.proofDataUrl || e.proofUrl;
      if (u && !imageUrls.includes(u)) {
        imageUrls.push(u);
      }
    });
    if (trip.cashLedger?.entries) {
      trip.cashLedger.entries.forEach((e) => {
        const u = (e as any).proofDataUrl || e.proofUrl;
        if (u && !imageUrls.includes(u)) {
          imageUrls.push(u);
        }
      });
    }
    if ((trip as any).proofs && Array.isArray((trip as any).proofs)) {
      (trip as any).proofs.forEach((p: any) => {
        const u = p?.proofDataUrl || p?.dataUrl || p?.url || p?.proofUrl;
        if (u && !imageUrls.includes(u)) {
          imageUrls.push(u);
        }
      });
    }

    // Fault-Tolerant Parallel Fetching for attached proof/receipt images
    const fetchWithTimeout = async (url: string, timeoutMs: number = 8000): Promise<string | null> => {
      if (!url || typeof url !== 'string') return null;
      if (url.startsWith('data:image')) return url;
      if (!firebaseService) return null;

      try {
        const timeoutPromise = new Promise<null>((resolve) =>
          setTimeout(() => {
            console.warn(`[TripDossierPdfBuilder] Non-blocking timeout (${timeoutMs}ms) fetching image: ${url.substring(0, 60)}...`);
            resolve(null);
          }, timeoutMs)
        );

        return await Promise.race([
          firebaseService.getImageAsDataUrl(url).catch((err) => {
            console.warn(`[TripDossierPdfBuilder] Non-blocking fault fetching image:`, err);
            return null;
          }),
          timeoutPromise
        ]);
      } catch {
        return null;
      }
    };

    const settledResults = await Promise.allSettled(
      imageUrls
        .filter((u): u is string => !!u && typeof u === 'string')
        .map(u => fetchWithTimeout(u))
    );

    const base64List: string[] = settledResults
      .filter((r): r is PromiseFulfilledResult<string | null> => r.status === 'fulfilled')
      .map(r => r.value)
      .filter((b64): b64 is string => !!b64);

    const boxW = 89.0;
    const boxH = 65.0;
    const gapX = 6.2;
    const gapY = 6.0;
    const gridStartY = p3ImgY + 4.5;

    if (base64List.length === 0) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(148, 163, 184);
      doc.text('No attached proof / receipt images available for this trip.', margin, gridStartY + 10);
    } else {
      for (let i = 0; i < base64List.length; i++) {
        if (i > 0 && i % 6 === 0) {
          doc.addPage();
          const contY = drawSimplifiedHeader(doc);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(10);
          doc.setTextColor(30, 58, 95);
          doc.text('Proof / Receipt Images (Cont.)', margin, contY);
        }

        const idxOnPage = i % 6;
        const col = idxOnPage % 3;
        const row = Math.floor(idxOnPage / 3);
        const x = margin + col * (boxW + gapX);
        const y = gridStartY + row * (boxH + gapY);

        // Border around image
        doc.setDrawColor(203, 213, 225);
        doc.setLineWidth(0.3);
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(x, y, boxW, boxH, 2, 2, 'FD');

        // Draw Image inside border with padding
        const imgFormat = base64List[i].includes('image/png') ? 'PNG' : (base64List[i].includes('image/webp') ? 'WEBP' : 'JPEG');
        try {
          doc.addImage(base64List[i], imgFormat, x + 2, y + 2, boxW - 4, boxH - 4, undefined, 'FAST');
        } catch {
          try {
            const altFormat = imgFormat === 'PNG' ? 'JPEG' : 'PNG';
            doc.addImage(base64List[i], altFormat, x + 2, y + 2, boxW - 4, boxH - 4, undefined, 'FAST');
          } catch {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(7.5);
            doc.setTextColor(148, 163, 184);
            doc.text('[ Image Preview Unsupported ]', x + boxW / 2, y + boxH / 2, { align: 'center' });
          }
        }
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 UNIVERSAL FOOTER ACROSS ALL PAGES
    // ─────────────────────────────────────────────────────────────────────────
    const pageCount = doc.getNumberOfPages();
    for (let p = 1; p <= pageCount; p++) {
      doc.setPage(p);
      const footerY = pageHeight - 8;

      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.3);
      doc.line(margin, footerY - 2, pageWidth - margin, footerY - 2);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);

      const footerText = p === 1
        ? 'PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY'
        : `PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY | ${formattedDate}`;

      doc.text(footerText, margin, footerY + 1.5);
      doc.text(`Page ${p} of ${totalPagesExp}`, pageWidth - margin, footerY + 1.5, { align: 'right' });
    }

    if (typeof doc.putTotalPages === 'function') {
      doc.putTotalPages(totalPagesExp);
    }

    const cleanFileName = `Trip_Details_Report_TLO_${tloNum}_${timestamp}.pdf`;
    doc.save(cleanFileName);
  }
}
