import ExcelJS from 'exceljs';
import { TripDispatch, COHEntry } from '../../models';
import { PORBIDO_LOGO_BASE64 } from '../../constants/report-logo.constant';
import { formatAppDate } from '../../utils/date-formatter';
import { TripDossierProofItem } from './export.types';
import { TripFinancialMetricsCalculator } from './trip-financial-metrics.calculator';

export class TripDossierExcelBuilder {
  static async build(
    trip: TripDispatch,
    cohEntries: COHEntry[] = [],
    proofItems?: TripDossierProofItem[],
    uploadBase64Image?: (base64: string, folder: string) => Promise<string>
  ): Promise<void> {
    const timestamp = this.getFileTimestamp();
    const tloNum = trip.tloNumber ? String(trip.tloNumber) : '';
    const tripNum = trip.tripNumber !== undefined ? String(trip.tripNumber) : '';
    const plateNum = trip.plateNumber || '';
    const driver = trip.driverName || '';
    const helper = (trip.helperName && trip.helperName !== 'None' && trip.helperName !== 'Unassigned') ? trip.helperName : '';
    const metrics = TripFinancialMetricsCalculator.compute(trip, cohEntries);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Porbido TMS';
    workbook.lastModifiedBy = 'Operations Administrator';
    workbook.created = new Date();
    workbook.modified = new Date();

    const thinBorder: Partial<ExcelJS.Borders> = {
      top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
    };

    const now = new Date();
    const formattedDate = `${now.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    })} • ${now.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    })}`;

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 WORKSHEET 1: COMPANY INFO
    // ─────────────────────────────────────────────────────────────────────────
    const infoSheet = workbook.addWorksheet('Company Info', {
      views: [{ showGridLines: true }]
    });

    infoSheet.columns = [
      { width: 5 },   // A: Left margin
      { width: 28 },  // B: Key
      { width: 55 },  // C: Value
      { width: 20 },  // D: Right margin
    ];

    // Embed Brand Logo
    if (PORBIDO_LOGO_BASE64) {
      try {
        const logoId = workbook.addImage({
          base64: PORBIDO_LOGO_BASE64,
          extension: 'png'
        });
        infoSheet.addImage(logoId, {
          tl: { col: 1, row: 1 },
          ext: { width: 220, height: 62 }
        });
      } catch {
        // Fallback gracefully
      }
    }

    // Row heights for logo spacing
    infoSheet.getRow(1).height = 18;
    infoSheet.getRow(2).height = 18;
    infoSheet.getRow(3).height = 18;
    infoSheet.getRow(4).height = 18;
    infoSheet.getRow(5).height = 12; // spacer

    // Row 6: Company Header Block
    const r6 = infoSheet.getRow(6);
    r6.getCell(2).value = 'PORBIDO TRUCKING & HAULING SERVICE';
    r6.getCell(2).font = { name: 'Arial', size: 13, bold: true, color: { argb: 'FF1E3A5F' } };
    r6.height = 20;

    const r7 = infoSheet.getRow(7);
    r7.getCell(2).value = 'ZONE 1 SAN VICENTE EAST, URDANETA CITY';
    r7.getCell(2).font = { name: 'Arial', size: 10, color: { argb: 'FF64748B' } };
    r7.height = 16;

    infoSheet.getRow(8).height = 12; // spacer

    // Row 9: Metadata Section Header
    const r9 = infoSheet.getRow(9);
    r9.getCell(2).value = 'DOCUMENT AUDIT PROFILE';
    r9.getCell(2).font = { name: 'Arial', size: 11, bold: true, color: { argb: 'FF1E3A5F' } };
    infoSheet.mergeCells('B9:C9');
    r9.getCell(2).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF1F5F9' }
    };
    r9.getCell(2).border = {
      top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
    };
    r9.height = 22;

    const metaItems = [
      { key: 'Document Title', val: 'TRIP DETAILS & FINANCIAL DOSSIER' },
      { key: 'Trip Reference (TLO #)', val: tloNum || '—' },
      { key: 'Trip Number', val: tripNum ? `Trip #${tripNum}` : '—' },
      { key: 'Fleet Plate Number', val: plateNum || '—' },
      { key: 'Assigned Driver', val: driver || '—' },
      { key: 'Assigned Helper', val: helper || '—' },
      { key: 'Generation Date & Time', val: formattedDate },
      { key: 'Generated By', val: 'Operations Administrator' },
      { key: 'Confidentiality Level', val: 'OFFICIAL USE ONLY (PROPRIETARY)' }
    ];

    let currentInfoRow = 10;
    for (const item of metaItems) {
      const row = infoSheet.getRow(currentInfoRow);
      row.getCell(2).value = item.key;
      row.getCell(2).font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF475569' } };
      row.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      row.getCell(2).border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };

      row.getCell(3).value = item.val;
      row.getCell(3).font = { name: 'Arial', size: 10, color: { argb: 'FF1E293B' } };
      row.getCell(3).border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };
      row.height = 20;
      currentInfoRow++;
    }

    currentInfoRow++; // spacer
    const rFooter1 = infoSheet.getRow(currentInfoRow);
    rFooter1.getCell(2).value = 'PORBIDO TMS — CONFIDENTIAL & PROPRIETARY | FOR AUTHORIZED OFFICIAL USE ONLY';
    rFooter1.getCell(2).font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF94A3B8' } };
    currentInfoRow++;

    const rFooter2 = infoSheet.getRow(currentInfoRow);
    rFooter2.getCell(2).value = 'System-generated document';
    rFooter2.getCell(2).font = { name: 'Arial', size: 8.5, italic: true, color: { argb: 'FF94A3B8' } };

    // ─────────────────────────────────────────────────────────────────────────
    // 📊 WORKSHEET 2: OVERVIEW & FINANCIALS (Pure Data with Spacing)
    // ─────────────────────────────────────────────────────────────────────────
    const sheet1 = workbook.addWorksheet('Overview & Financials', { views: [{ showGridLines: true }] });
    sheet1.columns = [
      { width: 3 },   // A: Left spacer
      { width: 28 },  // B: Card 1 Key
      { width: 34 },  // C: Card 1 Val
      { width: 5 },   // D: Gap spacer between Card 1 and Card 2
      { width: 28 },  // E: Card 2 Key
      { width: 34 },  // F: Card 2 Val
      { width: 5 },   // G: Gap spacer between Card 2 and Card 3
      { width: 28 },  // H: Card 3 Key
      { width: 34 }   // I: Card 3 Val
    ];

    sheet1.getRow(1).height = 14; // Top breathing space

    // Row 2: 3 Upper Cards Headers
    sheet1.mergeCells('B2:C2');
    sheet1.getCell('B2').value = 'TRIP IDENTIFIERS';
    sheet1.getCell('B2').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getCell('B2').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    sheet1.getCell('B2').border = thinBorder;

    sheet1.mergeCells('E2:F2');
    sheet1.getCell('E2').value = 'OPERATIONS & ROUTE';
    sheet1.getCell('E2').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getCell('E2').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    sheet1.getCell('E2').border = thinBorder;

    sheet1.mergeCells('H2:I2');
    sheet1.getCell('H2').value = 'BILLING & RECONCILIATION';
    sheet1.getCell('H2').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getCell('H2').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    sheet1.getCell('H2').border = thinBorder;
    sheet1.getRow(2).height = 22;

    const origin = trip.origin || trip.originFrom || '';
    const dest = trip.destination || trip.destinationTo || '';
    const routeDisplay = (origin && dest) ? `${trip.routeTag ? trip.routeTag + ' - ' : ''}${origin} > ${dest}` : '';

    const bagsDisplay = trip.bagCount ? `${trip.bagCount} Bags` : (trip.cargo?.bagCount ? `${trip.cargo.bagCount} Bags` : '');
    const billingStatusDisplay = trip.billingStatus || '';
    const billingRefDisplay = (trip as any).billingReference || (trip as any).saNumber || '';
    const billingDateDisplay = formatAppDate((trip as any).billedDate || (trip as any).billingDate) || '';
    const billingAmtDisplay = (trip as any).billingAmount !== undefined ? (trip as any).billingAmount : ((trip as any).billedAmount !== undefined ? (trip as any).billedAmount : '');
    const reconRefDisplay = (trip as any).reconciliationReference || '';
    const reconStatusDisplay = (trip as any).reconciliationStatus || '';

    const row1Triples: [string, any, string, any, string, any][] = [
      ['TLO Number', tloNum, 'Route Tag', routeDisplay, 'Billing Status', billingStatusDisplay],
      ['Trip Number', tripNum, 'Fleet Plate', plateNum, 'Billing Reference / SA Number', billingRefDisplay],
      ['Client', trip.client || '', 'Driver', driver, 'Billing Date', billingDateDisplay],
      ['Dispatched Date', formatAppDate(trip.dispatchedDate || trip.dispatchedAt) || '', 'Helper', helper, 'Billing Amount (PHP)', billingAmtDisplay],
      ['Trip Status', trip.status ? trip.status.replace(/_/g, ' ') : '', 'Commodity Cargo', trip.commodity || trip.cargo?.commodity || '', 'Reconciliation Reference', reconRefDisplay],
      ['Completed Date', formatAppDate(trip.deliveredDate || trip.deliveredAt) || '', 'Number of Bags', bagsDisplay, 'Reconciliation Status', reconStatusDisplay]
    ];

    row1Triples.forEach((tripRow, idx) => {
      const rNum = 3 + idx;
      const r = sheet1.getRow(rNum);

      // Card 1 (Cols B-C)
      r.getCell(2).value = tripRow[0];
      r.getCell(2).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF1E3A5F' } };
      r.getCell(2).border = thinBorder;
      r.getCell(3).value = tripRow[1];
      r.getCell(3).font = { name: 'Arial', size: 8.5, color: { argb: 'FF262B35' } };
      r.getCell(3).border = thinBorder;

      // Card 2 (Cols E-F)
      r.getCell(5).value = tripRow[2];
      r.getCell(5).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF1E3A5F' } };
      r.getCell(5).border = thinBorder;
      r.getCell(6).value = tripRow[3];
      r.getCell(6).font = { name: 'Arial', size: 8.5, color: { argb: 'FF262B35' } };
      r.getCell(6).border = thinBorder;

      // Card 3 (Cols H-I)
      r.getCell(8).value = tripRow[4];
      r.getCell(8).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF1E3A5F' } };
      r.getCell(8).border = thinBorder;
      r.getCell(9).value = tripRow[5];
      r.getCell(9).font = { name: 'Arial', size: 8.5, color: { argb: 'FF262B35' } };
      if (typeof tripRow[5] === 'number') {
        r.getCell(9).numFmt = '#,##0.00';
        r.getCell(9).alignment = { horizontal: 'right' };
      }
      r.getCell(9).border = thinBorder;

      r.height = 19;
    });

    // Generous Vertical Spacer between Upper Cards and Financial Breakdown (Rows 9 & 10)
    sheet1.getRow(9).height = 12;
    sheet1.getRow(10).height = 12;

    // Row 11: 3 Financial Breakdown Cards Headers
    sheet1.mergeCells('B11:C11');
    sheet1.getCell('B11').value = 'GROSS FREIGHT REVENUE';
    sheet1.getCell('B11').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getCell('B11').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    sheet1.getCell('B11').border = thinBorder;

    sheet1.mergeCells('E11:F11');
    sheet1.getCell('E11').value = 'CREW EXPENSES';
    sheet1.getCell('E11').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getCell('E11').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    sheet1.getCell('E11').border = thinBorder;

    sheet1.mergeCells('H11:I11');
    sheet1.getCell('H11').value = 'CREW COMPENSATION';
    sheet1.getCell('H11').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getCell('H11').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    sheet1.getCell('H11').border = thinBorder;
    sheet1.getRow(11).height = 22;

    const baseFreightSubtotal = metrics.tonnage > 0 && metrics.baseRate > 0 ? (metrics.tonnage * metrics.baseRate) : (trip.rateType === 'FLAT_RATE' ? metrics.baseRate : '');

    const row2Triples: [string, any, string, any, string, any][] = [
      ['Master Base Rate (PHP)', metrics.baseRate > 0 ? metrics.baseRate : '', 'Fuel (PHP)', metrics.fuel > 0 ? metrics.fuel : '', 'Driver Salary Pay (PHP)', metrics.driverSalary > 0 ? metrics.driverSalary : ''],
      ['Scale Weight (Tonnage)', metrics.tonnage > 0 ? `${metrics.tonnage.toFixed(2)} Tons` : '', 'Toll Fees (PHP)', metrics.toll > 0 ? metrics.toll : '', 'Helper Salary Pay (PHP)', metrics.helperSalary > 0 ? metrics.helperSalary : ''],
      ['Base Freight Subtotal (PHP)', baseFreightSubtotal, 'Meals / Foods (PHP)', metrics.meals > 0 ? metrics.meals : '', '', ''],
      ['Re-route Fee (PHP)', trip.rerouteFeeApplied ? 3600 : (trip.rerouteFee || ''), 'Maintenance (PHP)', metrics.maintenance > 0 ? metrics.maintenance : '', '', ''],
      ['Extra / Demurrage (PHP)', trip.extraFees || '', 'Others (PHP)', metrics.others > 0 ? metrics.others : '', '', ''],
      ['Gross Freight Revenue (PHP)', metrics.grossFreight > 0 ? metrics.grossFreight : '', 'Total Crew Expenses (PHP)', metrics.totalDebit > 0 ? metrics.totalDebit : '', 'Total Crew Payroll (PHP)', metrics.totalCrewPayroll > 0 ? metrics.totalCrewPayroll : '']
    ];

    row2Triples.forEach((tripRow, idx) => {
      const rNum = 12 + idx;
      const r = sheet1.getRow(rNum);
      const isTotal = idx === 5;

      // Card 4: Gross Freight (Cols B-C)
      r.getCell(2).value = tripRow[0];
      r.getCell(2).font = { name: 'Arial', size: 8.5, bold: isTotal, color: { argb: isTotal ? 'FF2563EB' : 'FF1E3A5F' } };
      r.getCell(2).border = thinBorder;
      r.getCell(3).value = tripRow[1];
      r.getCell(3).font = { name: 'Arial', size: 8.5, bold: isTotal };
      if (typeof tripRow[1] === 'number') {
        r.getCell(3).numFmt = '#,##0.00';
        r.getCell(3).alignment = { horizontal: 'right' };
      }
      r.getCell(3).border = thinBorder;

      // Card 5: Crew Expenses (Cols E-F)
      r.getCell(5).value = tripRow[2];
      r.getCell(5).font = { name: 'Arial', size: 8.5, bold: isTotal, color: { argb: isTotal ? 'FFE11D48' : 'FF1E3A5F' } };
      r.getCell(5).border = thinBorder;
      r.getCell(6).value = tripRow[3];
      r.getCell(6).font = { name: 'Arial', size: 8.5, bold: isTotal, color: { argb: isTotal ? 'FFE11D48' : 'FF1E293B' } };
      if (typeof tripRow[3] === 'number') {
        r.getCell(6).numFmt = '#,##0.00';
        r.getCell(6).alignment = { horizontal: 'right' };
      }
      r.getCell(6).border = thinBorder;

      // Card 6: Crew Compensation (Cols H-I)
      r.getCell(8).value = tripRow[4];
      r.getCell(8).font = { name: 'Arial', size: 8.5, bold: isTotal, color: { argb: isTotal ? 'FF2563EB' : 'FF1E3A5F' } };
      r.getCell(8).border = thinBorder;
      r.getCell(9).value = tripRow[5];
      r.getCell(9).font = { name: 'Arial', size: 8.5, bold: isTotal };
      if (typeof tripRow[5] === 'number') {
        r.getCell(9).numFmt = '#,##0.00';
        r.getCell(9).alignment = { horizontal: 'right' };
      }
      r.getCell(9).border = thinBorder;

      if (isTotal) {
        r.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } };
        r.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEFF6FF' } };
        r.getCell(5).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF1F2' } };
        r.getCell(6).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF1F2' } };
        r.getCell(8).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F3FF' } };
        r.getCell(9).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F3FF' } };
      }
      r.height = 19;
    });

    // Generous Vertical Spacer before Financial Statement (Rows 18 & 19)
    sheet1.getRow(18).height = 14;
    sheet1.getRow(19).height = 14;

    // Row 20: Trip Financial Statement Header (Spanning Cols B to I)
    sheet1.mergeCells('B20:I20');
    sheet1.getCell('B20').value = 'TRIP FINANCIAL STATEMENT';
    sheet1.getCell('B20').font = { name: 'Arial', size: 10.5, bold: true, color: { argb: 'FF1E3A5F' } };
    sheet1.getRow(20).height = 24;

    // Table Headers
    const r21 = sheet1.getRow(21);
    sheet1.mergeCells('B21:D21');
    r21.getCell(2).value = 'ITEM DESCRIPTION';
    r21.getCell(5).value = 'CATEGORY';
    sheet1.mergeCells('F21:G21');
    r21.getCell(6).value = 'SUBTOTAL (PHP)';
    sheet1.mergeCells('H21:I21');
    r21.getCell(8).value = 'NET IMPACT (PHP)';

    [2, 3, 4, 5, 6, 7, 8, 9].forEach(col => {
      r21.getCell(col).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      r21.getCell(col).font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF1E3A5F' } };
      r21.getCell(col).border = thinBorder;
      r21.getCell(col).alignment = { horizontal: 'center', vertical: 'middle' };
    });
    r21.height = 20;

    const stmtData: [string, string, number, number][] = [
      ['1. Gross Freight Revenue', 'REVENUE', metrics.grossFreight, metrics.grossFreight],
      ['2. Crew Expenses (Fuel, Toll Fees, Meals / Foods, Maintenance, Others)', 'OUTFLOW', metrics.totalDebit, -metrics.totalDebit],
      ['3. Crew Compensation (Driver & Helper Salaries)', 'PAYROLL', metrics.totalCrewPayroll, -metrics.totalCrewPayroll]
    ];

    stmtData.forEach((sRow, idx) => {
      const rNum = 22 + idx;
      const r = sheet1.getRow(rNum);
      sheet1.mergeCells(`B${rNum}:D${rNum}`);
      r.getCell(2).value = sRow[0];
      r.getCell(2).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF1E3A5F' } };

      r.getCell(5).value = sRow[1];
      r.getCell(5).font = { name: 'Arial', size: 8.5, bold: true };
      r.getCell(5).alignment = { horizontal: 'center' };

      sheet1.mergeCells(`F${rNum}:G${rNum}`);
      r.getCell(6).value = sRow[2];
      r.getCell(6).numFmt = '#,##0.00';
      r.getCell(6).font = { name: 'Arial', size: 8.5 };
      r.getCell(6).alignment = { horizontal: 'right' };

      sheet1.mergeCells(`H${rNum}:I${rNum}`);
      r.getCell(8).value = sRow[3];
      r.getCell(8).numFmt = '+#,##0.00;-#,##0.00;0.00';
      r.getCell(8).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: sRow[3] >= 0 ? 'FF16A34A' : 'FFE11D48' } };
      r.getCell(8).alignment = { horizontal: 'right' };

      [2, 3, 4, 5, 6, 7, 8, 9].forEach(c => r.getCell(c).border = thinBorder);
      r.height = 19;
    });

    const r25 = sheet1.getRow(25);
    sheet1.mergeCells('B25:D25');
    r25.getCell(2).value = 'NET TRIP INCOME & PROFITABILITY';
    r25.getCell(2).font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF1E3A5F' } };

    r25.getCell(5).value = `${metrics.margin.toFixed(1)}% NET MARGIN`;
    r25.getCell(5).font = { name: 'Arial', size: 8.5, bold: true, color: { argb: metrics.netTripIncome >= 0 ? 'FF16A34A' : 'FFE11D48' } };
    r25.getCell(5).alignment = { horizontal: 'center' };

    sheet1.mergeCells('F25:G25');
    r25.getCell(6).value = metrics.netTripIncome;
    r25.getCell(6).numFmt = '#,##0.00';
    r25.getCell(6).font = { name: 'Arial', size: 9, bold: true, color: { argb: metrics.netTripIncome >= 0 ? 'FF16A34A' : 'FFE11D48' } };
    r25.getCell(6).alignment = { horizontal: 'right' };

    sheet1.mergeCells('H25:I25');
    r25.getCell(8).value = metrics.netTripIncome;
    r25.getCell(8).numFmt = '+#,##0.00;-#,##0.00;0.00';
    r25.getCell(8).font = { name: 'Arial', size: 9, bold: true, color: { argb: metrics.netTripIncome >= 0 ? 'FF16A34A' : 'FFE11D48' } };
    r25.getCell(8).alignment = { horizontal: 'right' };

    [2, 3, 4, 5, 6, 7, 8, 9].forEach(c => {
      r25.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: metrics.netTripIncome >= 0 ? 'FFF0FDF4' : 'FFFFF1F2' } };
      r25.getCell(c).border = thinBorder;
    });
    r25.height = 22;

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 WORKSHEET 3: CASH FLOW & TRANSACTIONS
    // ─────────────────────────────────────────────────────────────────────────
    const sheet2 = workbook.addWorksheet('Cash Flow & Transactions', { views: [{ showGridLines: true }] });
    sheet2.columns = [
      { width: 16 }, // A: Date
      { width: 45 }, // B: Description
      { width: 18 }, // C: Credit (PHP)
      { width: 18 }, // D: Debit (PHP)
      { width: 18 }  // E: Balance (PHP)
    ];

    sheet2.mergeCells('A2:E2');
    sheet2.getCell('A2').value = 'CASH FLOW SUMMARY';
    sheet2.getCell('A2').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };

    const cfHeaders = ['PREVIOUS CARRYOVER (PHP)', 'CASH ON HAND (PHP)', 'CREW EXPENSES (PHP)', 'ENDING CASH ON HAND (PHP)'];
    const cfHeadRow = sheet2.getRow(3);
    cfHeaders.forEach((h, i) => {
      const c = cfHeadRow.getCell(i + 1);
      c.value = h;
      c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      c.font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF64748B' } };
      c.border = thinBorder;
      c.alignment = { horizontal: 'center' };
    });

    const cfValRow = sheet2.getRow(4);
    const cfValues = [metrics.signedCarryover, metrics.totalCredit, metrics.totalDebit, metrics.endingBalance];
    cfValues.forEach((val, i) => {
      const c = cfValRow.getCell(i + 1);
      c.value = val;
      c.numFmt = '#,##0.00';
      c.font = { name: 'Arial', size: 9.5, bold: true, color: { argb: i === 1 ? 'FF16A34A' : (i === 2 || val < 0 ? 'FFE11D48' : 'FF1E3A5F') } };
      c.border = thinBorder;
      c.alignment = { horizontal: 'right' };
    });
    cfValRow.height = 20;

    // Transactions Table
    sheet2.mergeCells('A6:E6');
    sheet2.getCell('A6').value = `TRANSACTIONS JOURNAL (${cohEntries.length})`;
    sheet2.getCell('A6').font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF1E3A5F' } };

    const tHeaders = ['DATE', 'DESCRIPTION', 'CREDIT (PHP)', 'DEBIT (PHP)', 'RUNNING BALANCE (PHP)'];
    const rJournalH = sheet2.addRow(tHeaders);
    rJournalH.height = 20;
    rJournalH.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      cell.font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF1E3A5F' } };
      cell.border = thinBorder;
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
    });

    let runBalExcel = metrics.startingCOH;
    cohEntries.forEach((e) => {
      const amt = Number(e.amount) || 0;
      const isCredit = e.type === 'CREDIT';
      if (isCredit) runBalExcel += amt;
      else runBalExcel -= amt;

      const dateStr = formatAppDate(e.date || e.timestamp) || '';
      const dRow = sheet2.addRow([
        dateStr,
        e.description || '',
        isCredit ? amt : null,
        !isCredit ? amt : null,
        runBalExcel
      ]);
      dRow.height = 18;

      dRow.eachCell({ includeEmpty: true }, (cell, colNumber) => {
        cell.font = { name: 'Arial', size: 8.5, color: { argb: 'FF262B35' } };
        cell.border = thinBorder;
        cell.alignment = { vertical: 'middle', horizontal: colNumber === 1 ? 'center' : (colNumber === 2 ? 'left' : 'right') };
        if (colNumber === 3 && cell.value !== null) {
          cell.numFmt = '+#,##0.00';
          cell.font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FF16A34A' } };
        }
        if (colNumber === 4 && cell.value !== null) {
          cell.numFmt = '-#,##0.00';
          cell.font = { name: 'Arial', size: 8.5, bold: true, color: { argb: 'FFE11D48' } };
        }
        if (colNumber === 5) {
          cell.numFmt = '#,##0.00';
          cell.font = { name: 'Arial', size: 8.5, bold: true, color: { argb: runBalExcel >= 0 ? 'FF1E3A5F' : 'FFE11D48' } };
        }
      });
    });

    // Total Row in sheet2
    const tTotalRow = sheet2.addRow([
      'TOTAL',
      `${cohEntries.length} Transactions`,
      metrics.totalCredit,
      metrics.totalDebit,
      metrics.endingBalance
    ]);
    tTotalRow.height = 20;
    tTotalRow.eachCell({ includeEmpty: true }, (cell, colNumber) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      cell.font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF1E3A5F' } };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
        bottom: { style: 'double', color: { argb: 'FF1E3A5F' } },
        left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
        right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
      };
      if (colNumber === 2) {
        cell.font = { name: 'Arial', size: 8.5, italic: true, color: { argb: 'FF64748B' } };
        cell.alignment = { horizontal: 'left' };
      }
      if (colNumber === 3) {
        cell.numFmt = '+#,##0.00';
        cell.alignment = { horizontal: 'right' };
      }
      if (colNumber === 4) {
        cell.numFmt = '-#,##0.00';
        cell.alignment = { horizontal: 'right' };
      }
      if (colNumber === 5) {
        cell.numFmt = '#,##0.00';
        cell.alignment = { horizontal: 'right' };
      }
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 📄 WORKSHEET 4: PROOF IMAGES (EXACTLY 2 COLUMNS: Description, Image link)
    // ─────────────────────────────────────────────────────────────────────────
    const sheet3 = workbook.addWorksheet('Proof Images', { views: [{ showGridLines: true }] });
    sheet3.columns = [
      { width: 45 }, // A: Description
      { width: 28 }  // B: Image link (Hyperlink button)
    ];

    const hRowProof = sheet3.addRow(['Description', 'Image link']);
    hRowProof.height = 24;
    hRowProof.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      cell.font = { name: 'Arial', size: 9.5, bold: true, color: { argb: 'FF1E3A5F' } };
      cell.border = thinBorder;
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
    });

    // Gather proof items from either explicit proofItems or trip/coh data
    const proofsToExport: { description: string; rawUrl: string }[] = [];

    if (proofItems && proofItems.length > 0) {
      for (const p of proofItems) {
        if (p.url) {
          proofsToExport.push({
            description: p.title || p.category || 'Proof Document',
            rawUrl: p.url
          });
        }
      }
    } else {
      if (trip.podImageUrl) {
        proofsToExport.push({
          description: 'Proof of Delivery (POD)',
          rawUrl: trip.podImageUrl
        });
      }
      cohEntries.filter(e => !!e.proofUrl).forEach(e => {
        proofsToExport.push({
          description: e.description || 'Receipt Image',
          rawUrl: e.proofUrl!
        });
      });
    }

    // Fault-Tolerant Parallel Resolution for proof URLs
    const resolvedProofs = await Promise.allSettled(
      proofsToExport.map(async (proof) => {
        let finalUrl = (proof.rawUrl || '').trim();

        // If stored as base64 and uploader is available, upload in parallel
        if (finalUrl.startsWith('data:image/') && uploadBase64Image) {
          try {
            finalUrl = await uploadBase64Image(finalUrl, 'proofs');
          } catch (err) {
            console.warn('[TripDossierExcelBuilder] Non-blocking fault: Could not upload base64 proof to storage:', err);
          }
        }

        return {
          description: proof.description,
          finalUrl
        };
      })
    );

    let proofCount = 0;

    for (const res of resolvedProofs) {
      if (res.status !== 'fulfilled') continue;
      const proof = res.value;
      const finalUrl = proof.finalUrl;
      const isWebUrl = finalUrl.startsWith('http://') || finalUrl.startsWith('https://');

      let linkCellVal: any;
      if (isWebUrl) {
        linkCellVal = {
          text: 'Open Document',
          hyperlink: finalUrl,
          tooltip: 'Click to open document in browser'
        };
      } else {
        linkCellVal = 'No Link Available';
      }

      proofCount++;
      const r = sheet3.addRow([proof.description, linkCellVal]);
      r.height = 22;
      r.getCell(1).border = thinBorder;
      r.getCell(1).font = { name: 'Arial', size: 9, color: { argb: 'FF1E293B' } };
      r.getCell(1).alignment = { vertical: 'middle', horizontal: 'left' };
      r.getCell(2).border = thinBorder;
      r.getCell(2).alignment = { vertical: 'middle', horizontal: 'center' };
      if (isWebUrl) {
        r.getCell(2).font = { name: 'Arial', size: 9, bold: true, color: { argb: 'FF2563EB' }, underline: true };
      } else {
        r.getCell(2).font = { name: 'Arial', size: 8.5, italic: true, color: { argb: 'FF94A3B8' } };
      }
    }

    if (proofCount === 0) {
      const emptyRow = sheet3.addRow(['No Proof Documents Attached', '']);
      emptyRow.height = 22;
      emptyRow.getCell(1).border = thinBorder;
      emptyRow.getCell(1).font = { name: 'Arial', size: 8.5, italic: true, color: { argb: 'FF64748B' } };
      emptyRow.getCell(2).border = thinBorder;
    }

    // Write buffer & download
    const buffer = await workbook.xlsx.writeBuffer();
    const cleanFileName = `Trip_Details_Report_TLO_${tloNum || 'NA'}_${timestamp}.xlsx`;

    const blob = new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = cleanFileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }

  private static getFileTimestamp(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, '0');
    const day = now.getDate().toString().padStart(2, '0');
    const hours = now.getHours().toString().padStart(2, '0');
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const seconds = now.getSeconds().toString().padStart(2, '0');
    return `${year}-${month}-${day}_${hours}-${minutes}-${seconds}`;
  }
}
